### ISSUE TITLE
Subtasks are rendered at the same level as the parent task

### ISSUE THREAD

**Issue by darthmachina** [jamiebrynes7/obsidian-todoist-plugin#10]
A task with a subtask will both be rendered as top level tasks.

Fairly self-explanatory to reproduce.

**Comment by jamiebrynes7** [comment]
This has been released in [v1.2](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/v1.2) :tada:

**Comment by AndrewPetrov** [comment]
Sorry, but how to do opposite - reflect subtasks as they was created in Todoist? Now subtask levels just ignoring
