### ISSUE TITLE
Add ability to fold Projects and Sections

### ISSUE THREAD

**Issue by Bejasc** [jamiebrynes7/obsidian-todoist-plugin#101]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Todoist tasks can be grouped into projects.
They can be further grouped into sections within those projects

It would be great to be able to fold each of these, so that a particular section or project must be clicked to expand the tasks within the projects or sections. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jamiebrynes7** [comment]
This feature is now available in [v1.8.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.8.0)!
