### ISSUE TITLE
Could we get a link to the tasks itself in Todoist next to each of them either in text or icon?

### ISSUE THREAD

**Issue by isle99** [jamiebrynes7/obsidian-todoist-plugin#104]
**Is your feature request related to a problem? Please describe.**
It's neither a problem nor a bug, just a slight improvement when it comes to integration.

**Describe the solution you'd like**
I want every task to have a link to itself in Todoist next to itself in Obsidian.

**Describe alternatives you've considered**
I don't know any alternatives for this currently.

**Additional context**
/

**Comment by jamiebrynes7** [comment]
Hey @isle99, links to the task in Todoist are available through the right-click context menu.
