### ISSUE TITLE
Make "title" optional

### ISSUE THREAD

**Issue by ottsch** [jamiebrynes7/obsidian-todoist-plugin#109]
Would be nice to be able optionally not show any title because I might already have a heading above.

**Comment by g12r** [comment]
I had the same want. I submitted a PR making the title toggle-able.

**Comment by jamiebrynes7** [comment]
I think perhaps a better approach is to just remove the `title` option as a breaking change in a v2.0 release. Really, if you want a heading, the native Obsidian ones are just better for integrating into the rest of the application, theming, etc.

**Comment by g12r** [comment]
I worked a bit more on the TodoistQuery markup to accommodate eliminating the existing H4 title. If you just eliminate it, the existing refresh button still consumes space at the top, leading to a big gap between, say, the native Obsidian header above it and the first task. While I was floating the refreshTodos button, I went further and added an add todo button, and I made them all look similar to the native Obsidian edit-markdown-block button. 

I also added an 'appended date' format that happens to be how I like to see dates (on the same line as the task), with a enable/disable setting and the ability to put whatever moment format you want to use for your date formats. 

It's a bit of a heavy commit to do as an uncoordinated PR and I didn't know what you might be interested in terms of v2.0 changes, @jamiebrynes7.

[Changelog entries here](https://github.com/g12r/obsidian-todoist-plugin/commit/4921f15d50e2bfc8f516fec2ca7244a803cdce08#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)

GIF of updated buttons.
![todoist-plugin-updated-buttons](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/1812696/c7295e11-8019-4caa-b209-35353c1116df)

**Comment by clcoble** [comment]
> I worked a bit more on the TodoistQuery markup to accommodate eliminating the existing H4 title. If you just eliminate it, the existing refresh button still consumes space at the top, leading to a big gap between, say, the native Obsidian header above it and the first task. While I was floating the refreshTodos button, I went further and added an add todo button, and I made them all look similar to the native Obsidian edit-markdown-block button.
> 
> I also added an 'appended date' format that happens to be how I like to see dates (on the same line as the task), with a enable/disable setting and the ability to put whatever moment format you want to use for your date formats.
> 
> It's a bit of a heavy commit to do as an uncoordinated PR and I didn't know what you might be interested in terms of v2.0 changes, @jamiebrynes7.
> 
> [Changelog entries here](https://github.com/g12r/obsidian-todoist-plugin/commit/4921f15d50e2bfc8f516fec2ca7244a803cdce08#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)
> 
> ## GIF of updated buttons.
> <img alt="" height="80%" src="https://private-user-images.githubusercontent.com/1812696/260264188-c7295e11-8019-4caa-b209-35353c1116df.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODEzMjMsIm5iZiI6MTcwNDM4MTAyMywicGF0aCI6Ii8xODEyNjk2LzI2MDI2NDE4OC1jNzI5NWUxMS04MDE5LTRjYWEtYjIwOS0zNTM1M2MxMTE2ZGYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMTUxMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBjNTVlNTAwOTYyYzA3OWI1ZTIwNTkyYTMzMWNkOTkxYTdkMTM4ZjkyNDQwNmQxZjVkOWYxNjA3N2E2ZGQyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.07FgpzLQG0fu3doLfpW7PWw4ccUcmhFrbfHgYLeiog8">

This looks awesome! Could you help a novice out on how exactly I can install your changes to this plugin? I’m new to Obisidian as well as Github. Thanks!

**Comment by g12r** [comment]
Interesting... I think it's all governed by the CSS but I did depart from some of how the the TodoistQuery sets up the structure. The operative classes and markup are likely in this vicinity: 

https://github.com/g12r/obsidian-todoist-plugin/blob/bb78c1cd7cb47f2105599899c0b5cbe8c020d7c2/src/ui/TodoistQuery.svelte#L99

If you have a screen shot or repro, I can take a look when back from a trip. 

Unrelated, I've lost the task item checkboxes on my end and I need to go see what those stopped appearing in mid-Dec. No known code changes involved that I could see.

**Comment by clcoble** [comment]
> Interesting... I think it's all governed by the CSS but I did depart from some of how the the TodoistQuery sets up the structure. The operative classes and markup are likely in this vicinity:
> 
> https://github.com/g12r/obsidian-todoist-plugin/blob/bb78c1cd7cb47f2105599899c0b5cbe8c020d7c2/src/ui/TodoistQuery.svelte#L99
> 
> If you have a screen shot or repro, I can take a look when back from a trip.
> 
> Unrelated, I've lost the task item checkboxes on my end and I need to go see what those stopped appearing in mid-Dec. No known code changes involved that I could see.

Much appreciated but it’s now working for me somehow. Appreciate your changes to make this an even better plugin!

**Comment by jamiebrynes7** [comment]
As of [v1.12.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.12.0), the title parameter is now optional! 🎉
