### ISSUE TITLE
Section filters return no results

### ISSUE THREAD

**Issue by darthmachina** [jamiebrynes7/obsidian-todoist-plugin#11]
1. Create a project that includes a section (i.e. 'Test')
1. Add a task under that section
1. Create a `todoist` code block in Obsidian that uses the filter `/Test`
1. No results will be returned for that block in Preview mode

Creating the same filter within Todoist itself will return the task created above.

**Comment by jamiebrynes7** [comment]
As a quick update for this issue, the Todoist API returns a 501 response code if you include a section filter in the REST API endpoint which this plugin uses (`/rest/v1/tasks`). 501 means that its not implemented on the Todoist backend. 😬 (Related to #18 as to why you aren't seeing anything)

I've [asked them](https://twitter.com/jamiebrynes/status/1300531115925569539) if this is planned to be implemented in the future, but it may be the case that for now this won't be possible. 

A long term solution would be to migrate to the [Sync API](https://developer.todoist.com/sync/v8/) which opens up some other interesting possibilities, but also would require a fair bit of work. 

In the meantime, I'll add a note to the README that section filters are currently unsupported.

**Comment by darthmachina** [comment]
Well, crap. Spent a bit of time migrating all of my Todoist projects to using sections for Kanban vs labels. 

I was trying to decide where my project tasks would sit, might just have to do that in Obsidian directly instead of through this. I tend to mix tasks and notes, though, so that was probably the more likely route.  My main use case for this plugin is all of my repeating tasks anyway, so this plugin already saves me a ton of work.

**Comment by jamiebrynes7** [comment]
For what its worth, I do plan to looking into using the Sync API in the future, but it requires more bookkeeping for the plugin so the REST API was the path of least resistence to get started.

So.. watch this space 😉

**Comment by thammawat-s** [comment]
Now this works fine.  FYI

$ curl -X GET \
  https://api.todoist.com/rest/v1/tasks \
  -H "Authorization: Bearer $token"

**Comment by jamiebrynes7** [comment]
I'm still getting `501: Unsupported filter keyword` when attempting to use the section filters, I wonder if it needs to be escaped differently 😕 

@thammawat-s how did you manage to get section filters working?

**Comment by thammawat-s** [comment]
sorry my bad.  I still get the same 501: Unsupported filter keyword.  :(

**Comment by thammawat-s** [comment]
Update.  Tech support replied me, now these should work.  Thanks to Omar from Todoist.    

query by section_id:
GET https://api.todoist.com/rest/v1/tasks?section_id=12345

Or filter on the section name using /sectionname:
GET https://api.todoist.com/rest/v1/tasks?filter=/mysection

**Comment by darthmachina** [comment]
I can confirm that filters using sections now works in the plugin, so this bug can be closed.

**Comment by jamiebrynes7** [comment]
That's awesome! Thanks for following up all.
