### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by isle99** [jamiebrynes7/obsidian-todoist-plugin#112]
**Describe the bug**
The latest release mentions a context menu, but I can't seem to find a way to trigger it.

**To Reproduce**
1. Go to queried Todoist tasks.
2. Right click on tasks.
3. Nothing happens.

**Expected behavior**
I expected to get a context menu.

**Screenshots**
/

**Desktop (please complete the following information):**
 - Plugin Version [e.g. 1.7.0]
 - Obsidian Version [e.g. 0.12.5]

**Additional context**
/

**Comment by jamiebrynes7** [comment]
Fixed in [`v1.7.1`](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.7.1)!
