### ISSUE TITLE
Ability to sort by date descending

### ISSUE THREAD

**Issue by seatrout** [jamiebrynes7/obsidian-todoist-plugin#114]
I would like to be able to sort by date descending, as well as the present method of sorting by ascending dates, which means that the tasks I put in most recently, and are this likely to be most urgent, are right at the bottom of the list.

**Comment by jamiebrynes7** [comment]
This feature is now available in [v1.8.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.8.0)!
