### ISSUE TITLE
Project and Section show up as unknown during onboarding session

### ISSUE THREAD

**Issue by webdevotion** [jamiebrynes7/obsidian-todoist-plugin#118]
**Describe the bug**
Project and Section show up as _unknown_.

**To Reproduce**
1. install plugin ( for the first time )
2. activate plugin
3. configure plugin
4. paste plugin block in markdown document
5. show preview
6. tasks show up, but project and section show up as _unknown project_ and _unknown section_.
7. close Obsidian
8. open Obsidian
9. check same markdown document
10. seems to work now

**Expected behavior**
When onboarding the plugin should show projects and sections as expected.

**Screenshots**
Not available: works as expected after restarting Obsidian.

**Desktop (please complete the following information):**
 - Plugin Version [e.g. 1.8.0]
 - Obsidian Version [e.g. 0.12.12]

**Additional context**
n/a

**Comment by jamiebrynes7** [comment]
I expect this is a race condition in fetching the required data from Todoist's API. I'm currently rewriting the API integration to use the Sync API which should eliminate these issues.

**Comment by webdevotion** [comment]
Thank you for the feedback. 

A minute ago the plugin failed to fetch the newly created tags from the new tasks I created in Todoist. They were gracefully rendered as `unknown label`. 

Restarting Obsidian fixed the issue ( exactly like the previous quick fix mentioned above ).

**Comment by jamiebrynes7** [comment]
You can also run the 'Refresh Metadata' command which I think should resolve these issues without a restart

**Comment by danielelliotr** [comment]
I am having a similiar issue where the projects on my list just show up as Uknown Project. 
![CleanShot 2023-10-17 at 14 28 46@2x](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/32912818/b89c9205-b8b7-4a31-9170-4b5f60727409)

**Comment by jamiebrynes7** [comment]
I've rewritten the API layer in the latest release. While it is still possible to see these elements (if we haven't pulled the data from Todoist yet), it should more reliably resolve itself or via the "Sync with Todoist" command.

I'm going to close this for now, if it seems like its a _persistent_ problem I'll revisit this again

**Comment by Dezaku** [comment]
![image](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/68233398/151328e0-305f-4e26-8ba0-6da771a9e89a)
got this too and can't seem to fix it

**Comment by schoenwaldnils** [comment]
I'm also still having this issue currently

**Comment by b11e** [comment]
> I'm also still having this issue currently

same, though I'm going to wait a bit in case it's due to me just recently creating the project
