### ISSUE TITLE
Can't scroll down

### ISSUE THREAD

**Issue by mrDLSable** [jamiebrynes7/obsidian-todoist-plugin#12]
When trying to scroll down in my note with the todoist script, the note keeps being scrolled back up, not always all the way back to the top.

**Comment by jamiebrynes7** [comment]
Hey @mrDLSable are you able to give more information around this issue? I'm unable to reproduce this.

- How long is the note? 
- Is auto-refresh on? 
- What version of Obsidian & this plugin?

**Comment by mrDLSable** [comment]
It's really annoying to reproduce, but I'll give as much info as I can.

I am on Obsidian version 0.8.9 and the plugin version 1.1.

I am using these todo lists all on the same note:

```todoist
{
"name": "Very Important",
"filter": "today & p1 | overdue & p1",
"autorefresh": 30
}
```

```todoist
{
"name": "Important",
"filter": "today & p2 | overdue & p2",
"autorefresh": 30
}
```

```todoist
{
"name": "Less Important",
"filter": "today & p3 | overdue & p3",
"autorefresh": 30
}
```

```todoist
{
"name": "Not Very Important",
"filter": "today & No priority | overdue & No Priority",
"autorefresh": 30
}
```
![image](https://user-images.githubusercontent.com/1783781/91813629-4696da00-ec33-11ea-9a41-0166348f85fa.png)

I have a lot of todo items due (72 right now) which might influence it.

It does the scrolling back up to the top regardless of whether I have autorefresh specified or not. Sometimes it takes a couple of seconds before it pulls me back up to the top and other times it keeps pulling me to the top every scroll action.

I have tried it with one big todo list (with all 72 items) and it still does it. I have tried it with custom CSS enabled and disabled and it always does it.

**Comment by jamiebrynes7** [comment]
Hmm, I'm still unable to reproduce this bug 😕. I have a note with a filter that currently captures and displays 78 todo items and I can scroll to the bottom of the note and it won't ever budge by itself.

What other plugins do you have enabled? I wonder if there is some interplay between different plugins.

**Comment by mrDLSable** [comment]
I have been trying to get a solid method to reproduce this, but sometimes it does it and other times it doesn't, so for now I'll just close this.

**Comment by jamiebrynes7** [comment]
Please do re-open this if you get a reliable repro 😃

**Comment by mrDLSable** [comment]
Will do 👍
