### ISSUE TITLE
Obsidian todoist token is saved on ".obsidian\\todoist-token" on Linux

### ISSUE THREAD

**Issue by argenos** [jamiebrynes7/obsidian-todoist-plugin#121]
**Describe the bug**
I recently upated the todoist plugin, and was asked to enter my token despite having it on the `.obsidian/todoist-token` file. Since I track my vault with git, I'm sometimes lazy and add all files without paying attention and I almost accidentally commited the new token file because it's saved as ".obsidian\\todoist-token" on Linux.

**To Reproduce**
Steps to reproduce the behavior (**on Linux**):
1. Update to latest version (sorry, I don't remember which version I was on before)
2. Check git status

**Expected behavior**
The file `.obsidian/todoist-token` would have been detected or the file created by the menu would follow Linux path conventions

**Screenshots**
![image](https://user-images.githubusercontent.com/5426039/130585417-008d8abf-e83d-4788-af17-76ca3d14335d.png)

**Desktop (please complete the following information):**
 - Plugin Version: 1.8.0
 - Obsidian Version: 0.12.14

**Additional context**
Should have a clause in this if for Linux: 
https://github.com/jamiebrynes7/obsidian-todoist-plugin/blob/cabf216c2b0f17101b2e717ff7c4bb9ea90b6601/src/token.ts#L7-L9

**Comment by jamiebrynes7** [comment]
Ah apologies, I introduced this when adding mobile compatibility in 1.8.0, should be a quick and easy hotfix though!

**Comment by jamiebrynes7** [comment]
Should be fixed in [1.8.1](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.8.1)

**Comment by argenos** [comment]
Thanks for the quick reply and bug fix! Can confirm it's fixed!
