### ISSUE TITLE
Add classes for styling *entire* task by priority

### ISSUE THREAD

**Issue by ScottKillen** [jamiebrynes7/obsidian-todoist-plugin#122]
**Is your feature request related to a problem? Please describe.**

I would like to style an entire task, and its meta, by priority. Currently, only the check box and task description can be styled by priority.

**Describe the solution you'd like**
Wrap each task in a style class (_Preferred_), or add a priority class to **every** element of a task.

**Comment by jamiebrynes7** [comment]
Released in v1.10.0
