### ISSUE TITLE
Add css class wrapping queries that return no results

### ISSUE THREAD

**Issue by ScottKillen** [jamiebrynes7/obsidian-todoist-plugin#123]
**Is your feature request related to a problem? Please describe.**
I would like to hide queries and their titles that return no tasks

**Describe the solution you'd like**
I would like css classes added to the div that wraps query results. This tag would indicate whether the query was empty. Perhaps `todoist-query-nonempty`, `todoist-query-empty`, and `todoist-query-error` wrapping, respectively, queries that contain tasks, queries that only contain the todoist success message, and queries that have failed.

**Comment by jamiebrynes7** [comment]
This is now released in [v1.12.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.12.0) 🎉
