### ISSUE TITLE
Include taskid when materialising Todoist tasks in Obsidian

### ISSUE THREAD

**Issue by richardlm** [jamiebrynes7/obsidian-todoist-plugin#124]
**Describe the solution you'd like**
I see this as a quick, interim solution while #117 (editing tasks in Obsidian) is developed 
e.g. https://todoist.com/showTask?id=1234567890

**Additional context**
Having two-way links between a task in Todoist and in Obsidian would be very useful.
We can already include the Obsidian page link in Todoist, including the Todoist link in Obsidian enables the round-trip.

**Comment by jebeaudoin** [comment]
Why was this feature request closed? I would find this very useful!

**Comment by gentlewatcher** [comment]
Can we get this re-opened or at least linked to what the resolution plan is?
