### ISSUE TITLE
Style not working

### ISSUE THREAD

**Issue by Nebucatnetzer** [jamiebrynes7/obsidian-todoist-plugin#129]
**Describe the bug**
I don't get any styling for the tasks.
All the boxes are just black.

**To Reproduce**
1. Install plugin and setup.

**Expected behavior**
Seeing the tasks colored by priority like in the gif.

**Screenshots**
![Screenshot from 2021-11-01 14-59-18](https://user-images.githubusercontent.com/2287221/139683610-3871ae3f-fcba-4adf-af53-878b8aa6e33b.png)

**Desktop (please complete the following information):**
 - Plugin Version 1.8.1
 - Obsidian Version 0.12.19

**Additional context**
I disabled any additional plugins and CSS snippets.

**Comment by bzimor** [comment]
You should use this [theme](https://github.com/jamiebrynes7/clair-de-lune-obsidian-theme) developed by this author in order to get those styles in demo gif.

**Comment by Nebucatnetzer** [comment]
I was under the impression that it should work with the default theme based on this sentence from the Readme.

```
This plugin comes with default CSS intended for use with the default Obsidian themes.
```
If that isn't the case then I'm rephrasing the question to this:
How can I create a CSS snippet from the provided example in the Readme?
I already tried to copy it 1:1 including the color.scss but must've overlooked something.

**Comment by bzimor** [comment]
One way to know the style you saw on demo is you should install this [theme](https://github.com/jamiebrynes7/clair-de-lune-obsidian-theme), then activate it and inspect task element by pressing `CTRL`+SHIFT+I`. You can see which css files are used for this
