### ISSUE TITLE
Include date/time if set on the task

### ISSUE THREAD

**Issue by darthmachina** [jamiebrynes7/obsidian-todoist-plugin#13]
If a task has a date or date/time set that should be rendered as part of the task.

Not sure if it would be helpful to render the date in the Daily Note date format or not, both since the tasks go away and I don't know if Obsidian would pick up on the link or not. But it would be nice to have it at least shown as part of the text.

**Comment by jamiebrynes7** [comment]
> I don't know if Obsidian would pick up on the link

It won't automatically, but the plugin possibly could attempt to construct the link itself (as it has access to the vault data).

**Comment by jamiebrynes7** [comment]
It should also probably add a css class to tasks which are overdue to allow users to style them differently if they choose to do so.

**Comment by darthmachina** [comment]
> It should also probably add a css class to tasks which are overdue to allow users to style them differently if they choose to do so.

That would be great to have. Right now I'm only seeing data and not even thinking of interesting ways to style the tasks.

**Comment by jamiebrynes7** [comment]
This has been released in [v1.2](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/v1.2) :tada:
