### ISSUE TITLE
Integrate using Moment or checking file title as input for filter function 

### ISSUE THREAD

**Issue by gentlewatcher** [jamiebrynes7/obsidian-todoist-plugin#136]
Trying to make the Filter section of the code block for a note, change based on the date for this note, its a daily note, with a title of the date.

**Describe the solution you'd like**
At the moment you are passing just the text for supported filters right into the api, if we can pass the "filter" text through something like Moment.js, or even obsidians connection to Moment.js which it uses for the daily note plugin or for Templated links even just the notes title as a variable, then use its output to give to your connection to the filter api.

**Describe alternatives you've considered**
Moment.js, or using variables that we can fill in by having it basically be an escape point that also calls obsidian api for its scripts or data like note title.

Or if you could have special filter inputs that would trigger these functions before continuing processes you already have in place.

**additional random notes or links**
https://forum.obsidian.md/t/daily-note-template-with-tomorrow-and-yesterday-links-and-annual-folders/27035

https://momentjs.com/docs/#/displaying/format/

https://help.obsidian.md/Plugins/Daily+notes

**Comment by gentlewatcher** [comment]
Sorry I was just rereading the main.js and on line 1660 var formatting tokens I say Moment formatting, so it should be easy to check for those in the filter input and then convert to text output before damping it into the api send.

**Comment by gentlewatcher** [comment]
Found my own work around using the templater plugin (https://silentvoid13.github.io/Templater/docs/) to set the variables myself and having them convert to string on new doc load from templates, but if there were a way for you to implement it a little smoother directly that would still be amazing.

**Comment by veigamann** [comment]
> Found my own work around using the templater plugin (https://silentvoid13.github.io/Templater/docs/) to set the variables myself and having them convert to string on new doc load from templates, but if there were a way for you to implement it a little smoother directly that would still be amazing.


Would you mind sharing your work around? I'm currently trying to implement the following query inside my daily note template, using Moment.js and the [Templater](https://github.com/SilentVoid13/Templater) plugin:

```
todoist

{
"name": "Today",
"filter": "<% moment(tp.file.title, 'YYYY-MM-DD').format('MM/DD/YYYY') %>"
}
```

However, I get this ` Error: There's a problem with your filter: "Unrecognized symbol <" `

I wanted to filter only the tasks for this specific day, so I'm able to see them afterwards. Don't know if that's possible. Anyway, thanks in advance.

**Comment by gentlewatcher** [comment]
I am sorry, I haven't messed with the main idea of this thread for nearly 10 months, last I had, I was using a daily notes "date format" as YYYY-MM-DD/filename with as a way to push it into a folder that then has todays (moment without having to be called like you tried) date , pulled that into todoist using tp.file.filder and I gave up and just settled on that.

ex:

```todoist
{
"name": "by end of <% tp.file.folder() %> these need to be done",
"filter": "due by <% tp.file.folder() %>",
"sorting": ["date"],
"group": true
}
```


But there has been updates since then. Like [tp.file.rename(new_title: string)](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/file-module.html) 

Hope that helps, I may get back into obsidian md. later but life is nuts at the moment.
