### ISSUE TITLE
Sort task by date/time

### ISSUE THREAD

**Issue by darthmachina** [jamiebrynes7/obsidian-todoist-plugin#14]
Somewhat related to #13 , the main Todoist interface will sort the tasks by date/time if set on the tasks. It would be nice to include this sort on the tasks rendered in Obsidian.

To match Todoist tasks with a date and time are rendered first and then tasks with a date but no time and then tasks with no date or time.

**Comment by jamiebrynes7** [comment]
This has been released in [v1.2](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/v1.2) :tada:
