### ISSUE TITLE
Retrieve Todoist task's description?

### ISSUE THREAD

**Issue by jamie9090** [jamiebrynes7/obsidian-todoist-plugin#147]
Would love to be able to retrieve the tasks's description as well as the task name!

**Comment by abers** [comment]
This would be great, as could then add links to Obsidian notes within the task description.

**Comment by seagullmouse** [comment]
I am just working on this. See example below with my bulleted description for my morning routine.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/1561613/190619379-81960f9d-a78c-4cab-aa95-f18cd906c6d0.png">

I'll submit a PR for review

**Comment by seagullmouse** [comment]
https://github.com/jamiebrynes7/obsidian-todoist-plugin/pull/175/files

**Comment by willl03** [comment]
This will be more than useful, thanks !

**Comment by jamiebrynes7** [comment]
This has been released as part of v1.11.0! 🎉
