### ISSUE TITLE
Show tasks that are assigned to me or to specific people

### ISSUE THREAD

**Issue by HammyHavoc** [jamiebrynes7/obsidian-todoist-plugin#150]
**Is your feature request related to a problem? Please describe.**
Seeing tasks that aren't mine is annoying.

**Describe the solution you'd like**
For it to mirror my 'Today' view on Todoist.

Being able to create code blocks for others would be a good way of visualizing what team members are doing on a dashboard page.

**Comment by jamiebrynes7** [comment]
Hey @HammyHavoc, a late reply to this... but can't you do this by controlling the filter?

For example, to get all tasks due today or overdue that are either assigned to you or not in shared projects:

```yaml
filter: "(today | overdue) & (!shared | assigned to: me)"
```

There are lots of [options](https://todoist.com/help/articles/introduction-to-filters-V98wIH) for filtering out tasks based on assignment.

**Comment by HammyHavoc** [comment]
We dropped Todoist a couple years back (no dependencies for tasks), but if we do return to it, I'll absolutely be doing this—would have been hugely useful at the time. My cous still uses it though, so I'll let him know, he will be thrilled.

Thanks! :- )
