### ISSUE TITLE
Error: Too Many Requests

### ISSUE THREAD

**Issue by Wittionary** [jamiebrynes7/obsidian-todoist-plugin#151]
**Describe the bug**
I get an error "Too Many Requests" though I have the interval set to 600 seconds.

**To Reproduce**
It's intermittent. I can say that it only started happening more frequently within the past couple weeks. It's never had an issue with a high-refresh interval before (to my memory). This happens on multiple networks. I've only been able to test on my work laptop - but I also primarily use the TD plugin just for work.

**Expected behavior**
I expect to not have that error - or to have the error be less interruptive/intrusive.
My tasks are currently there, in memory or some sort of cache, but if the GET fails my tasks disappear. I think if the request fails, it should of course provide a notification or icon that there's an issue (much like how the Todoist native app notifies you're offline), but still exposes the tasks to me. Even if I'm looking at stale data, that's still providing value.
It's also irritating to have your notes shift up and down since the error block is shorter than the block of tasks.

**Screenshots**
![image](https://user-images.githubusercontent.com/1906737/160637847-e34ae49d-fb32-44bb-8d03-da303a15546d.png)

**Desktop (please complete the following information):**
 - Plugin Version 1.9.0
 - Obsidian Version 0.14.2

**Additional context**

**Comment by sollymay** [comment]
Facing the same issue but no matter if reading/preview mode is on or not.

**Comment by ryanlaner** [comment]
Seeing the same issue on iOS regardless of view I am in.  Few days ago it was intermittent.  Today it is stuck on too many requests error.

**Comment by Banesmagic** [comment]
Same issue on both macOS and iOS.

**Comment by anvimea** [comment]
Same issue on Windows 10, Obsidian 0.14.2.

**Comment by jamiebrynes7** [comment]
Hey all, investigated this a little bit today. I've not experienced this myself and did some checks on Obsidian 0.14.2 to see if the plugin is making more requests than expected, this does not seem to be the case.

> Is the plugin making a request to the Todoist API every time I make an edit to the note in Live Preview mode

It will only make a request if you edit the Todoist code fence block, forcing a re-render. Edits elsewhere in the note won't trigger a request. 

- Each code block will make a request every N seconds, where N is specified globally in the plugin settings or the value of `autorefresh` in the code fence block. 
- If you use live preview, then both the code block in live preview and the normal rendered mode will be making requests, this effectively doubles the number of requests that are sent as there are two instances.
- The [Todoist REST API has rate limiting](https://developer.todoist.com/rest/v1/#request-limits). You can only make 450 requests every 15 minutes.

Given all of this, its possible that if you had enough Todoist code blocks rendered, each making requests at a high enough frequency that you will hit this rate limit and get this error back from Todoist. For example:

If you had 2 code blocks rendered, and you use live preview, and you have the auto-refresh set to 5 seconds you would be sending 48 requests per minute (2 * 2 * 60 / 5), which would exceed that rate limit.

Possible workarounds that you can try:

- Have less Todoist code blocks rendered at once
- Increase the "Auto refresh interval" in the settings

A long term solution would be to move across to the Sync API and do filtering on the Obsidian side, that way each code block doesn't need to make a request each, they can all draw from the same data source locally. I started work on this a little while ago, but it was larger in scope that I was anticipating and then found myself with less time.

**Comment by JohnKnoepfle** [comment]
I just started using this todoist plugin today (Obsidian v0.14.2) and I'm getting the same error.   I only have one single Todoist code block and I tried setting the auto-refresh to 600 and I'm still getting the "too many requests" error.

I get the error whether I have live preview on or not.

I'm able to create a todoist task with the "Add Todoist task" command - that works great.   

So far, I have not had any success displaying a list of tasks.

**Comment by Banesmagic** [comment]
This morning nothing works.  I turned of auto-refresh, waited a couple of hours and tried to update a single block, nothing.  None of my blocks render.

**Comment by jamiebrynes7** [comment]
@JohnKnoepfle If you open up the network tab of the developer tools ( Option + ⌘ + I (on macOS), or Shift + CTRL + I otherwise) and let it sit there for a while, how many requests to `api.todoist.com` do you see?

**Comment by jamiebrynes7** [comment]
Actually I just opened up mine and I'm getting the 'Too Many Requests' now, I'm wondering if this is a bug on Todoist's end which is causing issues as the plugin is behaviour correctly (and as before).

**Comment by JohnKnoepfle** [comment]
Hi @jamiebrynes7, 
Here are a couple of updates to my earlier comment.

First, I had a file open with the call to your plugin and all of a sudden it populated correctly on auto-refresh.   A few minutes later I got the error again.

Since then, I've been monitoring it in the network tab of the developer tools as you suggested for about an hour.   I was on a Zoom call and had it up and running so I could just glance at it while I was on the call :)    Interestingly, it does seem to be random.  Every time it auto-refreshes, there is only a single call at a time, but sometimes it works and sometimes it returns a 429 status code for too many requests.   I had blocks of 20 minutes or so where it worked fine, then blocks of 2 minutes where it would fail before it worked again.   The longest block I saw of 429 status codes was 11 straight minutes and then it started working again.

Let me know if there's anything else you need.

**Comment by jamiebrynes7** [comment]
Hey all! Todoist has said that they have deployed a fix for this issue. 🎉 

I'm going to leave this open for a week or so, but if no one is still experiencing issues after that I'll go ahead and close this!

**Comment by mjh-krk** [comment]
I think issue is back again.

Oh no, something went wrong!

Error: Request failed, status 429

429 = Too Many Requests

**Comment by jamiebrynes7** [comment]
Yeah I've been noticing this recently as well.

I can spy a bug fix in the latest Insider's release (~12 hours ago) that might be a clue though:

> Fixed bug where embeds and code blocks in Live Preview were not properly unloaded when switching files.

This would cause old queries to stick around and continue making requests, eventually there would be enough that we get rate limited.
