### ISSUE TITLE
Excessive spacing taken up when the Name field isn't used.

### ISSUE THREAD

**Issue by Wittionary** [jamiebrynes7/obsidian-todoist-plugin#152]
**Describe the bug**
When you don't include a value for "name" of the filter, a lot of padding/spacing is left at the top, reducing readability. I use a header so I can reference this block in other notes and for consistent formatting (H2). For me, the "name" field is excessive and reduces clarity.

**To Reproduce**
1. Create a new note
2. Copy/paste markdown:
```markdown
## Today's Focus
```todoist
{
"name": "",
"filter": "##myproject & today",
"sorting": ["priority"],
"group": true
}
```
3. Add 3 backticks to the bottom
4. Turn on Reading mode

**Expected behavior**
I expect all the content to shift upwards.

**Screenshots**
![image](https://user-images.githubusercontent.com/1906737/160642432-cf950dce-0a65-4f6e-b186-b1e33f4c2537.png)
![image](https://user-images.githubusercontent.com/1906737/160645193-0d207a0b-3f86-4ccb-a5f1-f05c4f772e6f.png)

**Desktop (please complete the following information):**
 - Plugin Version 1.9.0
 - Obsidian Version 0.14.2

**Additional context**

**Comment by jamiebrynes7** [comment]
This isn't a bug, more of a feature request as we'd need to relocate/optionally disable the refresh button as well. I'll merge this with #156 as they are similar requests!
