### ISSUE TITLE
New obsidian version with readable line length destroys format.

### ISSUE THREAD

**Issue by mmfs37** [jamiebrynes7/obsidian-todoist-plugin#153]
**Describe the bug**
The checkmark box is now not anymore completly visible through updating the version.
Everything worked awesome, I updated obsidian and now the checkmark thing isnt completly visible (for all tasks in every list)

**To Reproduce**
Install obsidian and plugin, log in and implement a list
Turn "readable line length" ON
update to the current newest obsidian version (29.03) 

**Expected behavior**
After the update you can only see the checkmark box for 5% the rest is not visible. The whole dataview is shifted to the left side. 

**Screenshots**
![image](https://user-images.githubusercontent.com/100991030/160689484-38807763-637f-41b3-9fb6-404376714bdb.png)

**Desktop (please complete the following information):**
 - Plugin Version: 1.9.0
 - Obsidian Version: v.0.14.2 (installer version: v.0.13.23)

**Additional context**
no other context

**Comment by mmfs37** [comment]
![image](https://user-images.githubusercontent.com/100991030/160690121-9e697843-81e1-4e10-9353-507586947932.png)

another screenshot because the last is a bit nonsaying
Yes the things on left side should be the colourful checkmarkboxes


Here a total screenshot of obsidian to see it in perspective
![image](https://user-images.githubusercontent.com/100991030/160690254-2f962fdc-bb5c-4726-9b4f-2f7efb6e7fec.png)

**Comment by jamiebrynes7** [comment]
Hey @mmfs37, this is likely an issue for the theme you are using. I cannot reproduce this with either the default Obsidian theme or the theme that I use day to day.
