### ISSUE TITLE
Unable to submit API on IOS mobile

### ISSUE THREAD

**Issue by BOD700** [jamiebrynes7/obsidian-todoist-plugin#154]
Hi,

Love the plugin, thank you!

I am having trouble loading API on mobile IOS after reinstall.. have been using successfully prior to this issue for a couple of weeks, also works on mac no problem.

Setup Todoist API Token just keeps popping up. Entered there, tried settings... no luck.

Can you help please?

Thanks again!

**Comment by BOD700** [comment]
Forget this thank you!

I reinstalled everything a few times and it is all good now...

**Comment by jamiebrynes7** [comment]
Glad it all worked out for you!
