### ISSUE TITLE
deactivate heading / name

### ISSUE THREAD

**Issue by mmfs37** [jamiebrynes7/obsidian-todoist-plugin#156]
**Is your feature request related to a problem? Please describe.**
I do want the option to deactivate name instead of leaving the space. it looks ugly if there is about 3 lines of space. I know that is also my fault with styling headings this way etc but still deactivating the name would be nice

**Describe the solution you'd like**
If this is typed:

"name": “”,
then there should be nothing. "" is the code for nothing, so the line for the title dissappears. 
Alternative would be 
"name":Null,

**Describe alternatives you've considered**
going in my style options and minimizing that heading that todoist plugin uses to minimum, and never using that heading for personal use ever again. 
but that would be a big price to pay, I love my different headings

**Additional context**

**Comment by marekbrze** [comment]
+1. 

I would love to use todoist task as an inline section without the name and extra space. I think only the filter value is needed and there should be a possibility to omit the name property

**Comment by KevinYobeth** [comment]
bump, is there any progress regarding this?

**Comment by jamiebrynes7** [comment]
Making this optional won't be too difficult - I'll look into this for the next release. As a possible workaround, you can add:

```css
h4.todoist-query-title {
	display: none;
}
```

as a custom CSS snippet to globally hide all query titles

**Comment by jamiebrynes7** [comment]
The title parameter is now optional as of [v1.12.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.12.0) 🎉 

Additionally, if the title is not provided, the header element is not rendered at all.
