### ISSUE TITLE
Support opening tasks in Todoist native iOS apps

### ISSUE THREAD

**Issue by jamiebrynes7** [jamiebrynes7/obsidian-todoist-plugin#158]
@jamiebrynes7 I can now see the context menu on mobile but "Open task in Todoist" doesn't do anything on iOS. However, I can complete tasks via the context menu.

_Originally posted by @laawn in https://github.com/jamiebrynes7/obsidian-todoist-plugin/discussions/127#discussioncomment-2104717_

**Comment by nabaco** [comment]
I see the same issue on Windows too. Open in Web works, but in App doesn't.

**Comment by jamiebrynes7** [comment]
This fix should now be released in [v1.12.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.12.0) 🎉
