### ISSUE TITLE
Able to push a new task from obsidian, but unable to view tasks in notes

### ISSUE THREAD

**Issue by raka-everton** [jamiebrynes7/obsidian-todoist-plugin#162]
So, clean install on the latest version 0.14.15. Added in the API token. 

I am able to create a todoist task from within obsidian, but when I use this simple command in a note

```todoist { "name": "My Tasks", "filter": "view all" } ```

It just appears as is and is not processed

Am I doing something wrong?
![unknown](https://user-images.githubusercontent.com/107866895/174670190-84332b5a-54c7-40ef-9fdf-bc5a016976a0.png)
?

**Comment by Superelmanu** [comment]
I do have the same problem.
I can add a task but I can't retrieve the tasks from todoist, even with the simplest filter or with the exemple given in the help part.

**Comment by Jokonu** [comment]
I had the same issue and couldn't figure out the problem, but it is only a formatting issue. Try using line breaks, then the rendering worked for me:


<div>
```todoist<br>
{<br>
	&nbsp&nbsp&nbsp&nbsp"name": "Todoist tasks",<br>
	&nbsp&nbsp&nbsp&nbsp"filter": ""<br>
}<br>
```
</div>

**Comment by jamiebrynes7** [comment]
Hey @raka-everton it has to be a code-fence block:

````markdown
```todoist
{
	"name": "Todoist tasks",
	"filter": ""
}
```
````

rather than an inline code snippet: 

````markdown
`todoist { "name": "Todoist tasks", "filter": ""`
````
