### ISSUE TITLE
Accommodate alternate config folder location

### ISSUE THREAD

**Issue by megclaypool** [jamiebrynes7/obsidian-todoist-plugin#170]
On the Obsidian About screen we have the ability to override the default config folder location. In my case, I prefer to separate the settings I use for different types of devices, so instead of using .obsidian, I use .obsidian_mac for my laptop and .obsidian_phone and .obsidian_ipad for my other devices.

However, in obsidian-todoist-plugin/src/token.ts you are hard-coding the location of the todoist api to the .obsidian folder:

```
export function getTokenPath(): string {
  return `.obsidian/todoist-token`;
}
```

Because I don't use the .obsidian folder, it doesn't exist. Each time I launch Obsidian, the Todoist plugin asks for my API. I enter it, but since the .obsidian folder doesn't exist the process silently fails. My workaround is to create that folder just to house the todoist-token file, but it would be a much better user experience if the plugin could check the config location, rather than assuming it's in .obsidian.

PS. Love the plugin, thanks for all your hard work ❤️ 😀

**Comment by jamiebrynes7** [comment]
This was released in v1.10.0!
