### ISSUE TITLE
what about lables?

### ISSUE THREAD

**Issue by swuphoto** [jamiebrynes7/obsidian-todoist-plugin#171]
**Is your feature request related to a problem? Please describe.**
I used labels for tasks, but there isn't seem to be a way to use a label as filters.

**Describe the solution you'd like**
add group by label, group by favorite

**Comment by Pejyuu** [comment]
I'm a bit late to this, but filter-options are available here over on the Todoist website 
https://todoist.com/help/articles/introduction-to-filters

**Comment by swuphoto** [comment]
thanks!
