### ISSUE TITLE
Todoist Plugin Error

### ISSUE THREAD

**Issue by micwaab** [jamiebrynes7/obsidian-todoist-plugin#177]
**Describe the bug**
Just this morning, the Todoist plugin stopped displaying my tasks and shows an error message (see screenshot.)

**To Reproduce**
1. Insert a todoist task codeblock
2. switch to reading mode

**Expected behavior**
I expect the Todoist task list to appear (and it always has, until this morning.) I have made no recent changes to Obsidian or my vault.

**Screenshots**
Todoist Plugin Module:
![CleanShot 2022-09-25 at 10 38 53@2x](https://user-images.githubusercontent.com/47571490/192152194-82e3aa5a-2ccf-497f-9eca-88aabf8f3915.png)

Console:
<img width="866" alt="CleanShot 2022-09-25 at 10 46 14@2x" src="https://user-images.githubusercontent.com/47571490/192152465-ebc08bca-63d3-4a75-959e-00278421b39a.png">

**Desktop (please complete the following information):**
 - Plugin Version: 1.9.0
 - Obsidian Version 0.16.3

**Additional context**
This just started out of the blue. No changes to my vault since yesterday, and the Todoist plugin was working fine at that time.

**Comment by micwaab** [comment]
Just wanted to update you on this. I uninstalled the plugin from Obsidian and reinstalled, but the issue did not change. Additionally, I created a new Todoist API and entered that into the plugin settings, but no change.

Thanks

**Comment by NaturallyAsh** [comment]
I am also experiencing this issue. Any solutions? Is there a plan to update to Todoist v2?

**Comment by jamiebrynes7** [comment]
@NaturallyAsh, @micwaab can you try the latest release v1.10.0? 

This contains the update to the REST API v2, which may fix this issue :smile:

**Comment by NaturallyAsh** [comment]
@jamiebrynes7 It works! Thanks mate!

**Comment by micwaab** [comment]
Thanks! Looks to be working again. Appreciate the notice!

**Comment by micwaab** [comment]
Sadly, this issue started again this morning.
