### ISSUE TITLE
The plugin will no longer work after Nov 1, 2022

### ISSUE THREAD

**Issue by aziham** [jamiebrynes7/obsidian-todoist-plugin#179]
**Describe the bug**
Today the plugin stopped working, I'm getting:

```
Oh no, something went wrong!
Error: Internal Server Error
```

**Screenshots**
![image](https://user-images.githubusercontent.com/94932043/193608493-f8dcae09-88a4-42f4-ac8a-bcc963735041.png)
![image](https://user-images.githubusercontent.com/94932043/193612278-6759a83d-d01a-484f-a6c0-5c180da9593c.png)
![image](https://user-images.githubusercontent.com/94932043/193608744-b42b5584-cb34-4950-82fe-9a730797e786.png)
![image](https://user-images.githubusercontent.com/94932043/193609133-8513ad24-6583-473a-b44f-9f9e89149d83.png)

**Desktop (please complete the following information):**
Plugin version: 1.9.0
Obsidian version: 0.15.9

**Comment by aziham** [comment]
- @pprazzi You are right. It was related to the maintenance.

![image](https://user-images.githubusercontent.com/94932043/193627324-d530649f-bac9-45d7-901d-c5fe60a4b414.png)

- Any idea if this maintenance is related to #176 ? 

![image](https://user-images.githubusercontent.com/94932043/193627853-9a54eb25-80dd-4802-a1dc-0415184aabda.png)

- As they stated that the v8 will no longer work after November 1
> The earlier will no longer be available after November 1

**Comment by aziham** [comment]
> * Any idea if this maintenance is related to [Todoist api v2 #176](https://github.com/jamiebrynes7/obsidian-todoist-plugin/pull/176) ?

![image](https://user-images.githubusercontent.com/94932043/193635344-a4893690-f15d-4559-987b-03883b68e0e2.png)
https://groups.google.com/a/doist.com/g/todoist-api/c/33g1sC_ov3Q

This confirms my assumptions that the V1 API will no longer work but it's actually after November 30.

- There's an open PR #176  by @gnapse addressing the API migration to V2.

@jamiebrynes7 Any plans for migrating to V2 ?

Thanks to all the people who made this plugin possible.

**Comment by jamiebrynes7** [comment]
Thanks for the heads up, I should probably join that google group!

I'll take a look at #176 on the weekend, or earlier if I find some time :)

**Comment by jamiebrynes7** [comment]
Hey all, tihs was released in v1.10.0!
