### ISSUE TITLE
Tasks completed in Obsidian aren't always completing in Todoist

### ISSUE THREAD

**Issue by anvimea** [jamiebrynes7/obsidian-todoist-plugin#185]
**Describe the bug**
Tasks completed in Obsidian aren't always completing in Todoist, and so are autopopulated back into the plugin as incomplete.

**To Reproduce**
1. Complete a task in Obsidian via Todoist plugin embed.
2. Check back later.
3. Task reappears in Todoist plugin embed.
4. Find task has not completed in Todoist.
5. Despair

**Expected behavior**
Tasks checked off in plugin embeds will also check them off in Todoist.

**Screenshots**

**Desktop (please complete the following information):**
- Latest plugin version, latest Obsidian version.

**Additional context**
This is a somewhat rare bug - I maybe encounter it once a day, and have for a few weeks now. 

Not sure how to represent it by screenshots, and not sure how to demonstrate how to reproduce it, since the plugin is mostly working fine for me; it's just once every few hours something I know I checked off in the plugin will reappear as incomplete.

**Comment by jamiebrynes7** [comment]
Hey @anvimea, are you still experiencing these issues? 

Todoist were having some general performance issues that were recently resolved (https://twitter.com/amix3k/status/1597941319510679552) that might have been the culprit.

**Comment by anvimea** [comment]
I haven't noticed it as much in awhile, so perhaps this was the problem! Gonna close this issue.
