### ISSUE TITLE
'Add Todoist Task' doesn't use highlighted text

### ISSUE THREAD

**Issue by fant5y** [jamiebrynes7/obsidian-todoist-plugin#187]
**Describe the bug**
I'd expected the option "Add Todoist Task" will add the currently highlighted text to my task, but nothing happened. The 'create new task' modal appears and I can fill out all the boxes and create a task. But there are no prefilled inputs with my selection neither is my selection stored in the description field of the task. 

Did I get the instructions wrong?

> 'Add Todoist task'
> This command opens up a modal for creating a task in Todoist. You can set the project/section, labels, priority, and due date through this modal. Any text selected when this command is executed will be pulled for the task content. 

**To Reproduce**
1. Highlight text in Obsidian
2. Press CTRL + P on Keyboard (Windows Desktop)
3. Search for _todoist_ and select _"Todoist Plugin: Add Todoist Task"_ and press enter
4. Modal appears with empty fields

**Expected behavior**
See description obove

**Screenshots**
Could provide a little screencast if needed.

**Desktop (please complete the following information):**
 - Plugin Version [1.10.0]
 - Obsidian Version [v1.0.3]

**Comment by jebeaudoin** [comment]
FWIW I encounter the same thing (Obsidian version [1.1.8], plugin version [1.10.0]). However, if I add the "Add Todoist Task" to the contextual menu with the Commander plugin, it does include the highlighted text as expected.
