### ISSUE TITLE
Project name getting rendered as 'unknown project'

### ISSUE THREAD

**Issue by aziham** [jamiebrynes7/obsidian-todoist-plugin#189]
**Describe the bug**
The project name is getting rendered as `unknown project`

**Screenshots**
![image](https://user-images.githubusercontent.com/94932043/203110812-bbfe9966-c6de-4674-8b3f-427318920904.png)

**Desktop (please complete the following information):**
Plugin version: 1.10.0
Obsidian version: 1.0.3

**Additional context**
Maybe this bug is related to #118 

**Weird behavior**
I've noticed a weird behavior when I kept restarting obsidian, sometimes the project name gets rendered just fine but sometimes it doesn't, not sure but maybe this is related to the REST API used in this plugin integration.

**Comment by aziham** [comment]
> I've noticed a weird behavior when I kept restarting obsidian, sometimes the project name gets rendered just fine but sometimes it doesn't

This behavior disappears after more than 10 restarts, now only the `unknown project` is returned.

**Comment by aziham** [comment]
After further testing I was able to solve this issue.

**Solution**
- I issued a new API token

I'm not sure if this solution is permanent neither what was the cause of the issue in the first place.

If anybody is faced with this issue please try the solution above and comment below if it did work for you or not.

**Comment by joshualukecaine** [comment]
> After further testing I was able to solve this issue.
> 
> **Solution**
> 
> * I issued a new API token
> 
> I'm not sure if this solution is permanent neither what was the cause of the issue in the first place.
> 
> If anybody is faced with this issue please try the solution above and comment below if it did work for you or not.

Issuing a new API token worked for me also
