### ISSUE TITLE
Sort tasks by priority

### ISSUE THREAD

**Issue by jamiebrynes7** [jamiebrynes7/obsidian-todoist-plugin#19]
Similar to #14, you should be able to sort by priority if desired.

**Comment by darthmachina** [comment]
If we do have multiple options to sort I would like to be able to combine them. e.g. sort by date/time first and then priority.

**Comment by jamiebrynes7** [comment]
This has been released in [v1.2](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/v1.2) :tada:
