### ISSUE TITLE
Cannot open multiple instances of the same query

### ISSUE THREAD

**Issue by seatrout** [jamiebrynes7/obsidian-todoist-plugin#203]
**Describe the bug**
When I have two or more notes open which contain the same query, either all, or all but one will fail with an error message, either 

`Error: net::ERR_NETWORK_IO_SUSPENDED`
or
`Error: Request failed, status 503`
sometimes
`Error: Request failed, status 504`

 

**To Reproduce**
Steps to reproduce the behaviour:

Open two or more notes which contain the same Todoist queries in quick succession. I am using the three below, but I suspect it has to do with their timing rather than their content.

```todoist
{
"name":"Routine, due today",
"filter":"(today|overdue) & recurring"
}
```

```todoist
{
"name":"Due today, not routine",
"filter":"(today|overdue) & !recurring"
}
```

```todoist
{
"name":"Planned/Upcoming",
"filter":"7 days & !recurring"
}
```

I have just restarted Obsidian. This note is, as I write, open in two places — on the sidebar and in the main body of the Obsidian window. There is also a journal note with one of these sections open in the main body. The sidebar copy and the journal entry are both failing to render, with error messages; the copy of the note in the main window is rendering properly. 
**BUT**
After I had been working on this bug report for a while, presumably for longer than the refresh interval, the problem suddenly switched, so that now the sidebar copy is rendering and the other two are showing an error message. See Screenshot.. 
_And when I switched back to Obsidian to take the screenshot, all three showed the same error message._ 

**Expected behaviour**
It should render in all three places. 
I suspect this is the result of a todoist api throttle against the same query being sent from the same IP address multiple times in quick succession. 
The workaround, in that case, is not to have the same query open in several notes in Obsidian. But this makes it difficult if, eg, the query forms part of a journal template and you are looking at several days' worth at once. 
The fix, if it is possible, would be for the plugin to keep track of requests and refuse to fire the same one off multiple times inside the Todoist throttle limit. But I don't know enough code to offer a tentative fix.  

**Screenshots**

**Desktop (please complete the following information):**
 - Plugin Version 1.1.9
 - Obsidian Version [e.g. 0.8.12]
 - Windows version: Edition	Windows 10 Home Version	22H2 OS build	19045.2364 Windows Feature Experience Pack 120.2212.4190.0

**Additional context**

**Comment by jamiebrynes7** [comment]
Hey there, both 503/504 errors indicate errors on the Todoist API's side - likely they were experiencing downtime. 

I regularly have the same query open (across multiple daily notes) and do not experience similar issues.
