### ISSUE TITLE
Add option to specify exact time when creating a task

### ISSUE THREAD

**Issue by pontifex9355** [jamiebrynes7/obsidian-todoist-plugin#204]
**Is your feature request related to a problem? Please describe.**
I'd like to specify exact time when creating a task. Currently only the date can be specified.

**Describe the solution you'd like**
When creating a task through the dialog, there should be an optional field for setting an exact time.
Additionally, it would be cool if we could use Todoist's [Quick Add](https://todoist.com/help/articles/task-quick-add) feature to just type the [date/time directly](https://todoist.com/help/articles/due-dates-and-times) in the task name and it would parse it and set correct values.

**Describe alternatives you've considered**
Currently I add a task through Obsidian, but I have to open the task in Todoist to adjust the time.

**Comment by ingewertwijn** [comment]
I would also love this. Any chance?

**Comment by jamiebrynes7** [comment]
I agree this would absolutely be a valuable feature. I can't say when I'll get around to it, but its on my radar :wink:

**Comment by vicyyn** [comment]
up, add this please x)

**Comment by yuschkof** [comment]
+1 I would love to use this function

**Comment by jamiebrynes7** [comment]
Hey all, I've rewritten the task creation modal in the [latest release](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.13.0) and added support for setting the due date time!
