### ISSUE TITLE
Tasks not displaying - Status 429 

### ISSUE THREAD

**Issue by kieranmansfield** [jamiebrynes7/obsidian-todoist-plugin#205]
My tasks for some reason are no longer showing up in Obsidian, I'm currently getting this error on every single query - `Error: Request failed, status 429`.

 - Plugin Version: 1.10.1
 - Obsidian Version: 1.1.9

**Comment by jaymehta-g** [comment]
I've been getting this all time time. "Status 429" means "too many requests" but at least for me I shouldnt be making enough requests to trigger that. Their website says the limit is 450 requests every 15 minutes and my todo list note only has 3 of the todoist displays, so I guess some bug with the plugin is sending way more requests than it really needs

**Comment by PSG2017** [comment]
Hi Jamie
I raised this issue with Todoist. They said: "Based on what we are seeing our logs it is starting to look like Obsidian may need to make some changes to how they are calling the Todoist API. Could you share a link to their site, forum, etc.?  I will attempt to reach out to them to see if we can take a deeper look together."
So sounds like they would be keen to work with you to assist if they can. I can point them to this page if you wish?

**Comment by jamiebrynes7** [comment]
@PSG2017 I'm glad the plugin is working for you, but I've not done anything on my end! Perhaps Todoist made some changes? 

Either way, if you would point them to this page please do :)

**Comment by PSG2017** [comment]
Hi Jamie
I've now heard that Todoist reset my counter at their end, which may explain the position.
I have pointed them at your page and the plugin page on Github and have indicated that you'd be happy for them to be in touch.
Hopefully they will be.
Thanks again for a great plugin.

**Comment by jamiebrynes7** [comment]
Closing this as it looks as though the issue has been resolved
