### ISSUE TITLE
Sort tasks by date added

### ISSUE THREAD

**Issue by bE7rwls** [jamiebrynes7/obsidian-todoist-plugin#206]
Is it possible to sort tasks by date added? 
"sorting": ["dateDescending"] or ["date"] are not moving tasks without dates

**Comment by jamiebrynes7** [comment]
Sure - this shouldn't be too difficult to add, the data exists in the API already

**Comment by jamiebrynes7** [comment]
This is now released in [v1.12.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.12.0) 🎉
