### ISSUE TITLE
Compiled plugin return "Function called outside component initialization" error

### ISSUE THREAD

**Issue by KevinYobeth** [jamiebrynes7/obsidian-todoist-plugin#208]
I want to contribute to obsidian-todoist-plugin, as I was setting my development environment, I compiled the plugin, and the dist folder got copied to the test-vault folder successfully, but when I ran the todoist query, it xoesn't work and return "Error: Function called outside component initialization" in the console

```
{
"name": "My Tasks",
"filter": "today | overdue"
}
```
![image](https://user-images.githubusercontent.com/10485985/214033271-a2c2af6e-71d2-4f1a-9502-5d078285c645.png)

**Comment by jamiebrynes7** [comment]
Hey @KevinYobeth, I'm unable to reproduce this issue on the `develop` branch. Are you still experiencing the issue?

**Comment by KevinYobeth** [comment]
Not anymore, I think I wasn't on develop branch last time I run the build script. Thanks!
