### ISSUE TITLE
Ability to search tasks in lists

### ISSUE THREAD

**Issue by thesamim** [jamiebrynes7/obsidian-todoist-plugin#210]
**Is your feature request related to a problem? Please describe.**
I have several todoist lists in my vault. I remembered that I have a task in the future. I can't search for tasks in Obsidian. I had to go to todoist. Not a huge deal, just a minor inconvenience. 

**Describe the solution you'd like**
It would be cool if Ctrl-F (when I'm in one of my lists) and Shift-Ctrl-F (when I can't remember which list it would be in) would also search in todoists lists.

I realize that the todoist results are only rendered when I open a particular document, so realize what I'm asking for is a TALL order.

Alternatively It would be cool to have a todoist plugin command in the command pallet that would the search for me. Possibly presenting a dialog with the "Get Active Tasks" parameters as selectable or fillable fields. 

**Describe alternatives you've considered**
Doing the search in the todoist interface is not that big a deal really.

**Additional context**
This is very low priority, a nice to have really. The plugin is phenomenal as it is.

**Comment by jamiebrynes7** [comment]
See https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/217#issuecomment-1500901665 for why searching natively in Obsidian is difficult.

> Alternatively It would be cool to have a todoist plugin command in the command pallet that would the search for me. Possibly presenting a dialog with the "Get Active Tasks" parameters as selectable or fillable fields.

This could be an interesting avenue to explore - although I'd need to change how the data syncing works, but that might come in the future with some other changes.

For now, I'm going to close this issue, but may reopen it in the future if it becomes feasible
