### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by robertandrews** [jamiebrynes7/obsidian-todoist-plugin#214]
Here's how it looks in the Default theme on the latest iPad app...

![IMG_1145](https://user-images.githubusercontent.com/3158787/221699163-64a6d329-120c-416f-b57f-3c0c411ddc13.jpeg)

There is:
- No indentation.
- No colour differentiation between title and secondary text.
- No separation between tasks.

Was the plugin designed to run on Minimal?
Here, too, I think there is:
- No separation between tasks.
- Ragged space between dates, tags etc.

![IMG_1146](https://user-images.githubusercontent.com/3158787/221699874-c3b27b13-d1be-4f18-ac42-d45f81b1dc67.jpeg)

**Comment by RobertTalbert** [comment]
I want to second this. The capabilities of this plugin are game-changing for me, but the visual clutter makes it hard to read. It would be nice to have the ability to select which metadata gets displayed.

**Comment by jamiebrynes7** [comment]
I completely agree that the extension needs a facelift - the original styling was more or less an MVP and struggles to scale across themes (and seemingly mobile platforms).

This is something that is on my radar but will be a relatively large chunk of work.

---

> Was the plugin designed to run on Minimal?

Not explicitly - although it looks like kepano has added support for it (https://github.com/kepano/obsidian-minimal/blob/master/src/scss/plugins/todoist.scss).

I use this theme and haven't noticed any glaring issues with the layout like above but I don't use tags in Todoist & almost exclusively use the "Live Preview" mode in Obsidian

**Comment by sicahjes** [comment]
Is there an update to this? I've just installed the plugin, but the lack of task separation makes it unusable for me. I'm new to YAML, so if there's something I'm meant to be doing that I've missed, I apologise.

**Comment by jamiebrynes7** [comment]
Hey all, I've redesigned and rewritten the task renderer in the latest release - this should be a bit nicer to work with and closer to how it feels in Todoist!
