### ISSUE TITLE
Is it possible to support Board view?

### ISSUE THREAD

**Issue by bmcclure** [jamiebrynes7/obsidian-todoist-plugin#219]
**Is your feature request related to a problem? Please describe.**
In Todoist, some of my projects are displayed in Board view, however embedding a query for that project in Obsidian shows a regular list of tasks.

**Describe the solution you'd like**
I'd love if Board view was supported somehow, but I don't know if it's possible.

**Describe alternatives you've considered**
I realize there is a Kanban plugin for Obsidian, but my tasks are in Todoist so it isn't a great fit for me.

**Comment by jamiebrynes7** [comment]
While it is possible to implement this, its not in my immediate plans - I do think this is a good idea, but I can't promise it will arrive anytime soon!

**Comment by SablinRoman** [comment]
@jamiebrynes7, do you have any plans for implementation?

**Comment by jamiebrynes7** [comment]
Duplicate of https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/142
