### ISSUE TITLE
Full descriptions do not appear

### ISSUE THREAD

**Issue by mutachre** [jamiebrynes7/obsidian-todoist-plugin#220]
I noticed that the ability to see the full descriptions of notes should have been implemented (#201), but still they do not appear in my notes. Why is that? Is there a filter (I have "@obsidian" enabled) or a specific configuration that does not allow this?

**Comment by rfearing** [comment]
@mutachre I was wondering the same thing. It appears @jamiebrynes7 hasn't released the change yet. What I just did was:
1. `git clone https://github.com/jamiebrynes7/obsidian-todoist-plugin.git`
2. `git checkout develop`
3. `npm i` and `npm run build`
4. Replace the files for the plugin in the Obsidian's plugin directory with the files generated in `build`

**Comment by jamiebrynes7** [comment]
Hey @mutachre, @rfearing, this change (along with others) have now been released as part of v1.11.0
