### ISSUE TITLE
Option to hide block of text when no results are returned

### ISSUE THREAD

**Issue by ddeighton** [jamiebrynes7/obsidian-todoist-plugin#221]
**Is your feature request related to a problem? Please describe.**
I would like to hide the block when a todoist query produces no results. 

**Describe the solution you'd like**
Instead of displaying "Nothing to-do! Sit back and relax.", I'd like to hide the block in Obsidian.

**Describe alternatives you've considered**
#123 could provide an alternative option to hide or alter the text displayed when no results are returned.

**Comment by jamiebrynes7** [comment]
You can now achieve this with custom CSS as the empty task list has a special class `todoist-no-tasks` released in [v1.12.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.12.0) 🎉
