### ISSUE TITLE
Todoist and Canvas

### ISSUE THREAD

**Issue by tempranello** [jamiebrynes7/obsidian-todoist-plugin#225]
Hello there

I've set up a homepage dashboard using a canvas. It works well except I cannot get the Todoist plugin to render in a card. 

My workaround is to simply create a note with my Todoist plugin query and then add that note on the canvas.

This works, but it doesn't look nice along with the rest of the cards.

The query I'm using is simple:

```todoist
{
"name": "",
"filter": "((today | overdue) | no date) & #Work"
}
```

As stated, it works fine in a note, but note in a canvas card.

Anyone else experience this?

**Comment by gstoel** [comment]
@tempranello why not embed todoist web itself on your canvas, that's how I do it. 
Has all the added benefits of being able to edit them straight from that page as well.

**Comment by jamiebrynes7** [comment]
This works okay for me in a Canvas card. Make sure you set the block language to `todoist`:

````
```todoist
filter: "today | overdue"
```
````
