### ISSUE TITLE
Markdown Todolists Conversion to Todoist

### ISSUE THREAD

**Issue by chenyenru** [jamiebrynes7/obsidian-todoist-plugin#231]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to add Todoist tasks separately.

**Describe the solution you'd like**

A feature that auto-converts markdown checklists to tasks and subtasks and auto-interprets the time written in some tasks as each respective task's schedule.

Below is an example:

- [ ] Correct P1 Practice Mon 19:30
	- [ ] 1
	- [ ] 2
- [ ] Vectors
	- [ ] Shortest Distance
	- [ ] 3 Planes Intersection
- [ ] Counting Principles
- [ ] Maclaurin Series
- [ ] Prob Distribution

--> It should do the following
1. Create separate task. 
2. Set the task "Correct P1 Practice" to the time **Mon 19:30**
3. Create subtask "1" and "2" for "Correct P1 Practice"
4. Create subtask "Shortest Distance" and "3 Planes Intersection" for "Vectors"

**Describe alternatives you've considered**
I can't really think of an alternative for this, apart from using Google Sheet to create the list and paste it to Todoist.

**Comment by chenyenru** [comment]
Here's a Pseudocode representation of a potential way to make it work. I will try working on it in the next few days:

## Pseudocode

- Use `- [ ]` as a separator
- If the current line has a tab (`&nbsp;`) in front, find the previous one and add the current to the subtask of the previous one.
- Remove the `- [  ]` in front
- Add it as a Todoist task with Todoist's [Quick Add Endpoint](https://developer.todoist.com/sync/v9/#quick-add-an-item)

```
- [ ] a
	- [ ] b
```

**Comment by Cameronwyatt** [comment]
@chenyenru this is an older thread so apologies if you've solved this, but this does seem possible to do with this plugin: https://github.com/HeroBlackInk/ultimate-todoist-sync-for-obsidian

**Comment by chenyenru** [comment]
Hey Cameron, it does! I'll look into it these few days
thank you
