### ISSUE TITLE
Not displaying tasks filtered by project.

### ISSUE THREAD

**Issue by johnborell** [jamiebrynes7/obsidian-todoist-plugin#235]
**Describe the bug**
Obsidian is not displaying Todoist tasks by project when filtered by project. 

**To Reproduce**
Insert the code:
```todoist
name: ToDo
filter: "#Inbox"
```
returns a list of all tasks, not just tasks associated with the Todoist Inbox. 

The same behavior regardless of what Project filter is used.

Other filters (e.g., filter: "today | overdue" or filter: @"LABEL") return the expected result

**Expected behavior**
A list of tasks by project when filtered by project.

**Screenshots**

**Desktop (please complete the following information):**
 - Plugin Version 1.11.1
 - Obsidian Version 1.3.5

**Additional context**
Filter by Project was working as expected yesterday; this behavior started today.

**Comment by jamiebrynes7** [comment]
This looks like it might be an issue on Todoist's end if the behaviour changed overnight - I'll forward this bug report to them.

**Comment by odsamuels** [comment]
Thanks for the ping @jamiebrynes7 🙏

I know we made a change yesterday but not one I anticipate should cause this.  Nevertheless, I will check on it and get back to you ASAP. 👍

**Comment by odsamuels** [comment]
Sorry for the turbulence. 🙏

We did introduce a bug with yesterday's change.

The great news is that we've now found it, fixed it, added tests for it, deployed it and everything should be back to the way it was before... well, not actually... with the recent change that we made you may notice decreased latency and increased speed for queries that may have previously taken a little longer. 💪🎉🎊

Thanks again for the ping @jamiebrynes7 .  I'm always happy to support in any way that I can. 🙇‍♂️

**Comment by johnborell** [comment]
@odsamuels Filtering is generally working again (thanks!). All "old" projects (before today) display property. But new projects do not name the project, but instead say, "Unknown project". See the screenshot below. That project is named "Test Project" in Todoist, but shows up as "Unknown project" in Obsidian.


![Screenshot 2023-06-01 at 8 41 26 PM](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/135251715/c852b6fd-2b7c-43bc-afd0-39e5f25b6d84)

**Comment by odsamuels** [comment]
@johnborell - Hmmm... I've been unable to reproduce a related issue so far.

Can you see any specific differences between the projects having issues and those that do not?

For example, Is the issue only manifesting for multi-word projects?  Does it also affect projects with one-word names?

Are you able to capture the logged errors for the calls with problematic results?

**Comment by johnborell** [comment]
It resolved itself, so I deleted the comment. Not sure what the issue was. 
 
Thanks again so much for fixing this so quickly today!

**Comment by jamiebrynes7** [comment]
Thanks @odsamuels for the quick response - we all appreciate it! :heart:
