### ISSUE TITLE
No styling

### ISSUE THREAD

**Issue by cgillett** [jamiebrynes7/obsidian-todoist-plugin#238]
**Describe the bug**
In this photo there is no styling
<img width="801" alt="Screenshot 2023-06-11 at 5 02 55 PM" src="https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/4927095/381da6ee-804e-4f33-a0dd-20c9702a8e52">

**Desktop (please complete the following information):**
 - Plugin Version 1.11.1
 - Obsidian Version 1.3.5
- Using Default theme

**Additional context**

**Comment by jamiebrynes7** [comment]
Fixed in latest release v2.0.0
