### ISSUE TITLE
Web & App Links - Not working

### ISSUE THREAD

**Issue by kieranmansfield** [jamiebrynes7/obsidian-todoist-plugin#240]
**Describe the bug**
Option to open a task in app or on web - neither option works on iOS.

**To Reproduce**
1. Long press a task
2. A menu will appear offer either open in app or in web

**Expected behavior**
Once tapping the menu, the link should open - however neither option does anything.

**Mobile:**
 - Plugin Version 1.11.1
 - Obsidian Version 1.4.6

**Additional context**

**Comment by jamiebrynes7** [comment]
Closing as a dupe of #158
