### ISSUE TITLE
Open in app doesnt work properly

### ISSUE THREAD

**Issue by chvainickas** [jamiebrynes7/obsidian-todoist-plugin#248]
**Describe the bug**
When I right click and press 'Open Task in Todoist(app)', it opens the app but not the task
**To Reproduce**
1. Right click task in obsidian
2. Choose 'Open Task in Todoist(app)'

**Expected behavior**
The task to open up in Todoist same as it does when I click 'Open Task in Todoist(web)', the open in web function works perfectly and opens up that specific task in Todoist on my browser

**Screenshots**

**Desktop (please complete the following information):**
 - Plugin Version [e.g. 1.1.1]
 - Obsidian Version [e.g. 1.3.7]

**Additional context**

**Comment by jamiebrynes7** [comment]
Hmm it looks like at some point Todoist removed support for the URI scheme (which in the in-app links use) on their desktop applications. The [documentation ](https://developer.todoist.com/guides/#mobile-app-url-schemes)now says that its only supported on iOS/Android (which would work except for #158).

I think I'll need to make this option conditional based on the platform

**Comment by jamiebrynes7** [comment]
Hey there, I've actually tested this on both Windows/MacOS and it seems to be working again! Given the URL format is correct, I'm going to close this issue
