### ISSUE TITLE
Overdue filter shows task which are closed

### ISSUE THREAD

**Issue by manfredlotz** [jamiebrynes7/obsidian-todoist-plugin#250]
Obsidian: 1.4.16
Todoist plugin: 1.11.1

**Describe the bug**
It happens the first time that the overdue filter shows 2 tasks which had been closed already.

**To Reproduce**

Create a filter like follows

```
```todoist
name: Overdue
filter: overdue
sorting:
   - date
```
```

Now two tasks are displayed which were closed already in September. In Todoist these tasks are not shown in overdue filter

**Comment by jamiebrynes7** [comment]
Hi @manfredlotz are you still experiencing this? Given the report, I'm leaning toward this being a Todoist issue. An easy way to test this if you encounter this again:

- Close all open files with the affected codeblock
- Reopen the file and wait for the codeblock to re-initialize
- If the offending tasks are still there, its likely a Todoist issue

The plugin does not maintain state outside of the rendered blocks, so if it displays immediately on first render, its just whatever we are getting from Todoist.

**Comment by manfredlotz** [comment]
Thanks @jamiebrynes7 

Your reasoning is very convincing. 

- I could not find those two tasks in the todoist app
- But using a command line tool I was able see those two tasks and could delete them (also by using the command line tool)
