### ISSUE TITLE
Can you add a new Command Palette option?

### ISSUE THREAD

**Issue by mtiowl** [jamiebrynes7/obsidian-todoist-plugin#253]
**Is your feature request related to a problem? Please describe.**
Not related to a bug, but related to how tasks are created in Todoist with the plugin.

**Describe the solution you'd like**
I would like to see a third option in the command palette.  This third option would create a link to the obsidian note in the description instead of the task name.  Very helpful when working on a project and adding multiple tasks or when I go back to a project note and need to add more tasks.  The link in the description can be a simple as [Link to Obsidian](obsidian://open?vault=......)

**Describe alternatives you've considered**
Every time I create a new task, I have to manually get the link to the note and paste it into the modal window.  This is very slow.

**Additional context**

**Comment by jamiebrynes7** [comment]
Hey @mtiowl, this is now available as a separate command in the [latest release](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.13.0).
