### ISSUE TITLE
Make it possible to create dynamic view

### ISSUE THREAD

**Issue by jalshorji** [jamiebrynes7/obsidian-todoist-plugin#254]
I would like to create dynamic view, to be used for templates. 

For example

```todoist
name: Tasks
filter: "#{{filename}}"
```

So, when I use this in my template, it will automatically filter on file name.

**Comment by gbrlsfernandez** [comment]
Not sure if you still need this, but you can use the Templater community plugin to achieve this.

Just add the tag below to achieve this:

filter: "<% tp.file.title %>"

**Comment by jamiebrynes7** [comment]
Hi, there's actually an open PR #246 which will add this functionality (specifically for file name)!

**Comment by jamiebrynes7** [comment]
This is now released in [v1.12.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.12.0) 🎉
