### ISSUE TITLE
Todoist Page got deleted on its own after Plugin crash

### ISSUE THREAD

**Issue by tormung83** [jamiebrynes7/obsidian-todoist-plugin#255]
**Describe the bug**
After installing and enabling the plug in, I used the sample code blocks in a new .md document file.

**To Reproduce**

I simply create a new Obsidian .md document which I called Todoist.
I then added the sample code blocks:

```todoist
name: My Tasks
filter: "today | overdue"
```

```todoist
name: Highest Priority & Date
filter: "today | overdue"
sorting: 
   - date
   - priority
group: true
```

I enabled the automatic refresh from the plugin settings which comes by default with the plugin. 
And after a few minutes, the .md file got deleted without any interaction. The plugin is still enabled though. 

**Expected behavior**
The file where I add the default sample code blocks should work as I am not even adding custom code blocks.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Plugin Version [e.g. 1.11.1]
 - Obsidian Version [e.g. 1.4.16]

**Additional context**
I installed the plugin from the Community plugins as I usually install them all.

**Comment by jamiebrynes7** [comment]
Hi @tormung83, this plugin doesn't interact with files at all, so I'm fairly confident in saying that this plugin is not the cause of the your file being deleted.
