### ISSUE TITLE
Bug: Section Filters stopped working

### ISSUE THREAD

**Issue by pdworkman** [jamiebrynes7/obsidian-todoist-plugin#263]
**Describe the bug**
Filters on /Section which were previously working have stopped working. I get "Request failed, Status 500" as a response

**Screenshots**

Error message:

![image](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/91858203/e927e0ed-64e9-413b-83ac-2724f3cdef38)

Embedded query:

![image](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/91858203/8c82ea03-d64f-41cb-ab57-da3ee440dd59)

The same query filter working inside Todoist:

![image](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/91858203/a86efc0a-5a5e-41c5-a1c1-429a42095fc8)

**Desktop (please complete the following information):**
 - Plugin Version [e.g. 1.2.0] 1.11.1
 - Obsidian Version [e.g. 0.8.12]  1.4.16

**Additional context**

I have not touched these queries. They were previously working. 

Queries by label are still working.

**Comment by holstuwe** [comment]
Con confirm this behaviour. This filter (section is "/⚡" for next actions, trying to implement GTD). 

(#A Kalender & (overdue|today)), (##A Areas & @arbeit & (overdue | today)), (##A Areas & @arbeit & /⚡), (##A Projekte & @arbeit & (overdue | today)), (##A Projekte & @arbeit & /⚡)

Result in Todoist:
![grafik](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/25038611/1d988eb4-fc86-4af0-9c6e-c52d48cfe5e0)

Same query in Obsidian:
```todoist
name: Todoist
filter: "(#A Kalender & (overdue|today)), (##A Areas & @arbeit & (overdue | today)), (##A Areas & @arbeit & /⚡), (##A Projekte & @arbeit & (overdue | today)), (##A Projekte & @arbeit & /⚡)"
```

Result: 
![grafik](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/25038611/c943d10f-0040-4986-9fa5-3f17b503295e)

This is the part which shows me results in Todoist itself: "##A Projekte & @arbeit & /⚡"

Show me all tasks within all subprojects of "A Projekte" (hence the ##) being in a section called "⚡" having the label "arbeit". 
![grafik](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/25038611/af59cdcf-6afb-4ed5-8b90-d576afd7c0d9)

Todoist version is v4923 (beta). Plugin is the latest version in Obsidian 1.5.3 (installer 1.4.16). 

Changing the filter in Obsidian to something simpler, for example:

```todoist
name: Todoist
filter: "/⚡"
```

Shows the correct result:
![grafik](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/25038611/7ac9ea48-6fff-4684-8331-adf5e4b94d05)

No error in console here.  Maybe the query is too complex for the api? Trying to get arround it with changing the query. 
Are comma separated queries not working with the api?

**Comment by holstuwe** [comment]
Changing the query to:

"(#A Kalender & (overdue|today)) | (##A Areas & @arbeit & (overdue | today)) | (##A Areas & @arbeit & /⚡) | (##A Projekte & @arbeit & (overdue | today)) | (##A Projekte & @arbeit & /⚡)"

using | instead of , works for me.

**Comment by pdworkman** [comment]
My queries started working again a day or two later without changing anything on my end.

**Comment by jamiebrynes7** [comment]
Looks like this was a transient issue on Todoist's end, considering it was working, not working, then started working again with no changes on the plugin side!
