### ISSUE TITLE
How it is working in Iframe?

### ISSUE THREAD

**Issue by rendomnet** [jamiebrynes7/obsidian-todoist-plugin#266]
Hello there, I would like to inquire about the functionality of the todoist iframe. I believe Todoist restricts its usage in iframes. Even when I attempt to load Todoist using chrome.declarativeNetRequest.updateDynamicRules in my chrome extension, it does not work. Could you kindly provide some insights on how you managed to resolve this issue?
Thank you in advance. I love obsidian.

**Comment by jamiebrynes7** [comment]
Hey @rendomnet, this plugin doesn't use iframes, it uses the [API](https://developer.todoist.com/rest/v2/) to pull data out of Todoist and materialize them within Obsidian.
