### ISSUE TITLE
Todoist tasks not showing checkboxes in Obsidian

### ISSUE THREAD

**Issue by macmartine** [jamiebrynes7/obsidian-todoist-plugin#267]
**Describe the bug**
I am successfully pulling in tasks into Obsidian from Todoist, but they don't show checkboxes

**To Reproduce**
1. Install plugin
2. Add snippet:
```todoist
name: Inbox 📥
filter: "#Inbox"
```

**Expected behavior**
Should show checkboxes by items

**Screenshots**
![image](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/378646/560bf892-f53f-4b65-a782-b150c1203d8e)

**Desktop (please complete the following information):**
 - Plugin Version 1.11.1
 - Version 1.5.3 (Installer 1.4.16)

**Additional context**

**Comment by jamiebrynes7** [comment]
Which theme are you using? Do you have any custom css?

**Comment by macmartine** [comment]
I figured it out - I was using the Minimal theme, and when I changed the theme it worked. Thanks
