### ISSUE TITLE
Ability to select shown field

### ISSUE THREAD

**Issue by JalilArfaoui** [jamiebrynes7/obsidian-todoist-plugin#276]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have a simple list of tasks, uncluttered of projects, tags and dates for each

**Describe the solution you'd like**
I would like to have new query fields:

```todoist
name: My Tasks
filter: "#someProject"
sorting: 
 - priority
show:
 - due
 - project
 - tags
 - description
```

**Describe alternatives you've considered**
I could work on a CSS snippet to hide unwanted properties, but it would be global to all queries.

**Comment by jamiebrynes7** [comment]
Hey @JalilArfaoui, thanks for the suggestion - this is already planned for the next release, see #130

**Comment by JalilArfaoui** [comment]
Wonderful !
