### ISSUE TITLE
Cannot install this plugin: Plugin ID mismatch

### ISSUE THREAD

**Issue by ras0q** [jamiebrynes7/obsidian-todoist-plugin#284]
**Describe the bug**
installing this plugin fails with a "Plugin ID mismatch" popup

**To Reproduce**

1. create a new vault
2. turn off restricted mode
3. try to install "Todoist Sync" plugin
4. then, the "Plugin ID mismatch" popup will display 

**Expected behavior**

You can install this plugin successfully.

**Screenshots**

![image](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/66677201/5cd059f1-4675-45de-ba81-e128c45afb5e)

**Desktop (please complete the following information):**
 - Plugin Version: Unknown (maybe after v1.12.0?)
 - Obsidian Version: v1.5.3

**Additional context**

**Comment by jamiebrynes7** [comment]
Hey @ras0q, sorry about this! This should now all be working correctly again 😅

**Comment by ras0q** [comment]
Thank you!

**Comment by froses** [comment]
When I update from 1.1.11 version to 1.12.0 version, the plugin cannot be loaded ("Failed to load plugin todoist-sync" message appears).

BUT I installed Todoist-sync without problems into the Obsidian Sandbox vault. So, I uninstalled the plugin in my other vaults and reinstalled it, and it seems to work.

Obsidian 1.5.4 (Installer version 1.5.3) and default theme.

**Comment by jamiebrynes7** [comment]
@froses you managed to update the plugin in the ~10 minute window while I was silently fixing that as well, I was hoping no one would be caught out by that one 🙈

**Comment by froses** [comment]
@jamiebrynes thanks a lot for your excellent plugin!
