### ISSUE TITLE
Group by section do not work

### ISSUE THREAD

**Issue by aZZmNZtA** [jamiebrynes7/obsidian-todoist-plugin#285]
Thanks a lot for the opportunity to use the plugin!

Doesn't show sections:

![10622_Obsidian_XkanC5kq](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/85443828/33404a25-c445-4d75-96a9-8c75427379bf)

Can this be fixed?

Thank you!

**Comment by dsuedholt** [comment]
I have the same issue sometimes. Running "Todoist Sync: Sync with Todoist" command from the command palette usually fixes it for me.

**Comment by jamiebrynes7** [comment]
Hey @aZZmNZtA, @dsuedholt - I recently aligned the grouping behaviour to match Todoist's filter view since we are building on top of the filters.

I do plan on expanding on this behaviour in the future, allowing grouping on (among other things) sections so that you have more flexibily in how things are rendered

**Comment by XvGt69** [comment]
Hey, 
I was going to ask the same thing . 
But I didn't really got it. The groupBy feature is not working yet in the current release ?

**Comment by jamiebrynes7** [comment]
Hey @XvGt69, the current release (v1.12) doesn't have the `groupBy` feature.

Its implemented and will be released with the next release there's a handful of things left I want to get done for the next release, so it shouldn't be _too_ long to wait!

**Comment by jamiebrynes7** [comment]
This is now released as part of [v1.13.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.13.0), you can do:

```yaml
filter: today | overdue
groupBy: section
```

To group by project & section.
