### ISSUE TITLE
Add obsidian note link to task description 

### ISSUE THREAD

**Issue by Gourav1910** [jamiebrynes7/obsidian-todoist-plugin#302]
Hi I just checked your plugin and it is working good. I just want an option when we create a task from obsidian in todoist then it also pastes a link of that obsidian note in the task title. I want that link to be in description and not in the task title itself. 

Currently I can do the same but deleting that text from the title and pasting into the description of that task. But it brings some resistance into the work. So it would be nice if you put an additional option in settings so that we can choose whether we want that link in title or in description.

**Comment by dennbo** [comment]
Hi! It would although be great to have an option to decide using standard obsidianURL or advancedURI. Kind regards

**Comment by jamiebrynes7** [comment]
This is now available in the [latest release](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.13.0) as an additional command!
