### ISSUE TITLE
priorityAscending and priorityDescending sort opposite

### ISSUE THREAD

**Issue by softwaresteph** [jamiebrynes7/obsidian-todoist-plugin#305]
**Describe the bug**
`priorityAscending` and `priorityDescending` sort in the wrong direction. **It is sorting by number instead of Priority** 

For example: 
P1 is the highest priority, so in `Descending`, it should be on top of the list. Instead, it is on the bottom 
P4 is the lowest priority, so in `Ascending`, it should be on top of the list, Instead, it is on the bottom. 

**To Reproduce**
Requirements: Have two tasks of differing priorities, let's say a P1 and P4
To your filter use:
```
sorting:
   - priorityAscending 
```

**Expected behavior**
- P4 
- P1 

** Actual behavior** 
- P1
- P4

**Screenshots**
**Ascending** 
![Screenshot 2024-04-04 at 16 58 43](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/39837332/6dfc46fe-d8a7-4440-8ef9-2f1f9c68a057)![Screenshot 2024-04-04 at 16 58 49](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/39837332/cf9c1510-ed09-4756-a6bd-63d5bebbc519)

**Descending** 
![Screenshot 2024-04-04 at 16 58 26](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/39837332/422e6609-c32f-4570-8c9e-3d1905fc5aba)![Screenshot 2024-04-04 at 16 58 33](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/39837332/7688b79d-a2be-4f8c-8d0b-cdbb0c438885)

**Recording**
<video src="https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/39837332/2ecc6e59-3425-45a0-a95f-75ac74a99e34"/>

**Desktop (please complete the following information):**
 - Plugin Version [e.g. 1.12.0]
 - Obsidian Version [e.g. 1.5.12]

**Comment by jamiebrynes7** [comment]
Hey @softwaresteph this should now be fixed in the [latest release](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.13.0)!
