### ISSUE TITLE
Commit as markdown on completion

### ISSUE THREAD

**Issue by mjsalam** [jamiebrynes7/obsidian-todoist-plugin#313]
Is there an option (or if not would love if there was) to have a task render as markdown to a note upon completion.  

For example: When I complete a task (before it disappears) it gets rendered to a particular section in my daily note (## completed or something like that).

Thanks!  Awesome plugin!

**Comment by jamiebrynes7** [comment]
Duplicate of https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/58
