### ISSUE TITLE
Please create an option to choose whether to include the title of the markdown page being edited in the task title.

### ISSUE THREAD

**Issue by Jack-KkKk** [jamiebrynes7/obsidian-todoist-plugin#316]
**Is your feature request related to a problem? Please describe.**
If I add a task by pressing the Add Task button in the query block, the task title is forced to insert the page I am currently editing, which is annoying. 

**Describe the solution you'd like**
When adding a task by pressing the Add Task button in the query block, it would be nice to have an optional setting to decide whether the page you are currently editing should be inserted into the task title, the task description, or neither. 

**Describe alternatives you've considered**
It would be really nice to have something like this in the options. 

**Additional context**
Thank you so much for creating such a fantastic plugin. The latest update is so beautiful and easy to use.

**Comment by k3rber0s-code** [comment]
Hey, I think you should mark it as a bug, because the standard addTask function should not include the page title in content.

**Comment by jamiebrynes7** [comment]
Hey there, this is now configurable in the settings in the latest (v2.0.0) release!
