### ISSUE TITLE
Label dropdown not working in task creation dialog

### ISSUE THREAD

**Issue by ofalvai** [jamiebrynes7/obsidian-todoist-plugin#321]
**Describe the bug**

**To Reproduce**
1. Have a Todoist code block
2. Click the ➕ icon
3. Click on the labels button

**Expected behavior**

It should contain my existing labels (I confirmed that I do have labels)

**Screenshots**

<img width="256" alt="image" src="https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/1694986/633c1734-1c38-4385-b8d5-6961a0f82d8e">

**Desktop (please complete the following information):**
 - Plugin Version [e.g. 1.2.0]
 - Obsidian Version [e.g. 0.8.12]

**Additional context**

**Comment by jamiebrynes7** [comment]
@ofalvai this is unusual! Does this happen reliably for you? Are there any error logs from the plugin in the dev console (`cmd + option + i` on Mac and `ctrl + shift + i` for Windows)?

**Comment by ofalvai** [comment]
Now that I tried again, the dropdown correctly displays my tags. Feel free to close this issue or keep open as you like. I'll report back if it happens again.
