### ISSUE TITLE
Kanban/Board View

### ISSUE THREAD

**Issue by Dezaku** [jamiebrynes7/obsidian-todoist-plugin#323]
**Is your feature request related to a problem? Please describe.**
The plugin is missing a support for a kanban/board view
**Describe the solution you'd like**
I would like to have a kanban/board view just like in Todoist but integrated into Obsidian best would of course be to be able to move them right in Obsidian
**Describe alternatives you've considered**
/
**Additional context**
/

**Comment by jamiebrynes7** [comment]
Duplicate of https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/142
