### ISSUE TITLE
Information not shown

### ISSUE THREAD

**Issue by tunix77** [jamiebrynes7/obsidian-todoist-plugin#325]
Hi

Thank you for making this Plugin! 

I did disable the legacy Options to not show Description, Tags and so on. 

``` todoist
name: "My Todoist Tasks on this Project"
filter: "# My Project"  
show:  
- due  
- description
- labels
- project
```

The Tasks are shown, but no further Information is shown within the Tasks. 

![todoist_1](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/125519132/d08972c8-8570-403e-ae6c-99fd8cc91dd4)
![todoist_2](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/125519132/23a471c3-bea2-4b4c-bc27-3f19f2f647b6)
![todoist_3](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/125519132/db9e8ce1-05f7-43a3-8446-cf05735df741)

It used to show all this information perfectly, also with a specific Filter for a Label -it used to show the Projects, the Task is located.

Am I doing something wrong? 

Desktop Obisidian: 1.6.5 (was the same before the last update) 
Todoist Sync App: 1.13.0

Thank you, 
Regards,
Thomas

**Comment by jamiebrynes7** [comment]
Hey if you don't want to use the legacy options - please leave them all on in the settings. Right now both are evaluated, so if the option in the settings is _off_ it will respect that
