### ISSUE TITLE
Tasks from some sub-projects show up but not from other sub-projects

### ISSUE THREAD

**Issue by ahafri** [jamiebrynes7/obsidian-todoist-plugin#327]
**Describe the bug**
When I have a filter for projects and sub-projects (see below), certain tasks in certain sub-projects appear but not in other sub-projects. It does not seem to be related to the title of the project (e.g., whether it contains characters like ":" or emojis). The same filter parameters appear to work fine in the Todoist application.

The filter used is:
```todoist
name: Work Today Tasks
filter: "##Work 🎯 & (today | overdue)"
sorting:
   - date
   - priority
group: false
```

**To Reproduce**
I am not sure how to reproduce it. But one attempt could be:
1. Create a main project with sub-projects, and tasks in sub-projects.
2. Create a filter view in the plugin.
3. See whether the tasks all appear in Obsidian.

**Screenshots**
<img width="512" alt="image" src="https://github.com/user-attachments/assets/b5ef9acf-3395-40d7-83df-9e98655b7669">
<img width="746" alt="image" src="https://github.com/user-attachments/assets/f87a50cd-3a3b-49b7-bb89-fd8c918f1930">

**Desktop: Mac OSX Sonoma 14.3.1**
 - Plugin Version: 1.11.1
 - Obsidian Version: 1.6.5

**Comment by jamiebrynes7** [comment]
I'm struggling to reproduce this bug, my initial thought is maybe Todoist isn't actually sending the tasks in the API response. 

If you enable debug logging from the plugin settings, the raw request/responses will be logged in the developer console - then we can see which tasks are actually returned by Todoist.

Are you able to reliably reproduce this with that specific query & project setup?

**Comment by ahafri** [comment]
You're right, Todoist isn't returning those tasks in the API response. Yet the same query works fine in the app proper (i.e., it returns from the sub-projects). I am kind of at a loss. 

Is there a way for me to directly test different queries in the console?

**Comment by jamiebrynes7** [comment]
There's a very roundabout way by reaching into the internals of the system! 

First you need to register a subscription:

```
const [_, refresh] = app.plugins.plugins['todoist-sync-plugin'].services.todoist.subscribe("##Test", (tasks) => console.log(tasks))
```

Then call the refresh callback to trigger the API call and then log to the console:

```
refresh()
```

This is asynchronous, so the tasks will appear a short while after you press enter

**Comment by ahafri** [comment]
OK, I just installed the latest plugin version (1.13.0), and the API call now gives me the requested data (it wasn't before, with plugin version 1.11.1). The query retrieved in the console and what's shown in the Obsidian note are in line with one another, so the issue appears to be that the query itself does not return all the tasks that it should, based on the filter (whereas in the Todoist app itself, the same query does).

I think I pinpointed the issue: The plugin (at least for me) appears to fail at retrieving tasks that are in sub-projects of sub-projects:

Here's the plugin:
<img width="774" alt="image" src="https://github.com/user-attachments/assets/284e61b8-7553-44ae-ba23-62e9b4f75a7e">

Here's the Todoist app. Notice the additional task from the "Recruiting and Branding 🆕" project (under the "Work 🎯" main project), under the section "Recruiting":
<img width="828" alt="image" src="https://github.com/user-attachments/assets/e038c2d1-323c-4e3b-86ea-8a4915097bb1">

The missing task ("Email undergrad...") is one embedded in "Work 🎯" > "Set Up Research 🔬" > ""Recruiting and Branding 🆕". When I put the very same task one project up (in "Set Up Research 🔬"), the plugin succeeds at retrieving it.

**Comment by jamiebrynes7** [comment]
> the API call now gives me the requested data (it wasn't before, with plugin version 1.11.1)

I take this to mean the code snippet I gave you didn't work until you updated? If so, yeah that's expected - sorry I missed you were on an old version! I rewrote the querying backend between those versions 😅 

> so the issue appears to be that the query itself does not return all the tasks that it should, based on the filter
> [...]
> I think I pinpointed the issue: The plugin (at least for me) appears to fail at retrieving tasks that are in sub-projects of sub-projects

This is great - thanks for tracing this down. I'll try and repro this myself, but regardless I'll raise an issue with Todoist (I don't work there and this is just an unofficial plugin) to try and get the API response fixed!

**Comment by ahafri** [comment]
Ah, that's great! Didn't think about the fact that the issue could be on Todoist's end, but of course, that makes sense. Looking forward to seeing the resolution. (And by the way, I *love* your plugin; thanks for making it!)

**Comment by jamiebrynes7** [comment]
Hey @ahafri - Todoist has fixed the issue! I just tested it again myself and it looks like the behaviour is working as expected now. 🎉
