### ISSUE TITLE
no time filter not working

### ISSUE THREAD

**Issue by mrDLSable** [jamiebrynes7/obsidian-todoist-plugin#33]
The following filter works in the todoist app/website but not in the plugin:

```no time & today```

obsidian: v0.8.12
plugin: v1.2.2

**Comment by jamiebrynes7** [comment]
Hey @mrDLSable, seems that you've ran into another unsupported filter keyword like #11 (despite the Todoist API docs claiming otherwise!).

I think I'll make a meta ticket to track these as and when we run into them.

**Comment by mrDLSable** [comment]
Ah, thanks @jamiebrynes7. I know it's a lot to ask for, but could you as a workaround perhaps assign a class to the todo items so people like me (probably just me) can hide them? Perhaps NoTime and HasTime?

**Comment by jamiebrynes7** [comment]
I'm happy to add a `has-time` or similar to the task element, but does that solve your problem completely? 

Unless you _never_ want to see tasks without time in any query, doing this at a CSS level will affect all queries.

**Comment by mrDLSable** [comment]
What I want to do is essentially use this query: ```overdue & p1 | today & no time & p1```. With the has-time I can then use the following query and CSS to simulate it.

```overdue & p1 | today & p1```

```css
.has-time{
    display: none;
}

.task-overdue{
    display: block;
}
```

I know it's just a bodge, but it's the best I can come up with right now.

**Comment by jamiebrynes7** [comment]
Sure I can add those classes in, I imagine they could be useful for someone else as well. 

Raised #36 for this 😄

**Comment by mrDLSable** [comment]
Thanks :) I really love the plugin so far and look forward to what you will be able to do when the official plugin API is released

**Comment by thammawat-s** [comment]
"filter": "no time"    is working now, FYI.

**Comment by jamiebrynes7** [comment]
Yup, can confirm `no time` works as a filter now! 🎉
