### ISSUE TITLE
Make the project name and due date dep-emphasized (smaller, gray) to distinguish from task name

### ISSUE THREAD

**Issue by ahafri** [jamiebrynes7/obsidian-todoist-plugin#330]
**Is your feature request related to a problem? Please describe.**
Currently the task name, project name, and due date are all the same font color and size. Therefore, the only thing separating the task name from the other two pieces of info are the indentation. This makes it difficult to quickly browse the task list in Obsidian to see what tasks I have.

**Describe the solution you'd like**
Make the font color of the project name and due date faded (e.g., gray), and perhaps smaller as well. Kind of like the font styling of the task description (see screenshot). I believe an older version of the plugin had this, but then in the newer version changed?

<img width="633" alt="image" src="https://github.com/user-attachments/assets/04027ceb-279a-4db8-bc48-8818ffb663d6">

**Comment by jamiebrynes7** [comment]
Hey @ahafri, there's actually a redesign that's landed in `master` and will be available with the next public release. As a sneak peak, this is what that looks like with the default theme:

![CleanShot 2024-08-05 at 16 25 40@2x](https://github.com/user-attachments/assets/b11dbbbb-e167-474f-b621-a01348cd0cc9)

The metadata elements are both smaller and use slightly more muted text, is this what you were thinking of?

**Comment by ahafri** [comment]
YES! This is brilliant. Looking forward to it. I'll close the feature request.
