### ISSUE TITLE
Problem with API token

### ISSUE THREAD

**Issue by bengtove** [jamiebrynes7/obsidian-todoist-plugin#336]
I'm trying to install Todoist Sync, but I got stuck after I supplied the API token. Submitting the token is impossible — the submit button doesn't work – and hitting return has no effect. I've created a new token, turned the plugin on and off, and restarted Obsidian, but this hasn't helped.

Any advice? If it makes any difference, I'm running Obsidian on a Mac.

**Comment by lightbluepoppy** [comment]
I had the same issue. Solved by issuing a new Token.

**Comment by gabb0z** [comment]
Same issue here. Using Obsidian 1.6.7 on MacOs.

Issuing a new token in todoist didn't solve the issue for me unfortunately.

**Comment by jamiebrynes7** [comment]
I've got a few reports of this, going to merge some of these issues together into https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/342
