### ISSUE TITLE
Could not set up plugin because Todoist API token was not accepted.  Repeated with a new token copy/pasted into plugin dialog box, but the 'Submit' button was never focused - clicking did nothing'S

### ISSUE THREAD

**Issue by LesWaymont** [jamiebrynes7/obsidian-todoist-plugin#337]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Plugin Version [e.g. 1.2.0]
 - Obsidian Version [e.g. 0.8.12]

**Additional context**

**Comment by MansyrevAY** [comment]
Happened to me as well, plugin does not recognize my api token

**Comment by MansyrevAY** [comment]
Issuing new token solved it for me

**Comment by jamiebrynes7** [comment]
I've got a few reports of this, going to merge some of these issues together into https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/342
