### ISSUE TITLE
Task info (project, date...) not showing

### ISSUE THREAD

**Issue by tmllull** [jamiebrynes7/obsidian-todoist-plugin#338]
**Describe the bug**
The information about the tasks is not showing.

**To Reproduce**
Create a simple query like:
````todoist
name: "Tareas para hoy (Todoist)"
filter: "today | overdue"
````

**Expected behavior**
As the key `show` is not set, all the related info for every task must be rendered, as the documentation says: "If omitted, all task metadata will be rendered."

**Screenshots**
Code:
![imagen](https://github.com/user-attachments/assets/22121515-6bf4-44d9-977c-41d0087d31b3)

Result:
![imagen](https://github.com/user-attachments/assets/9f81fa1e-6e88-4713-ae7c-cbdb1bca4f36)

**Desktop (please complete the following information):**
 - Plugin Version: 1.13.0
 - Obsidian Version 1.6.7

**Additional context**
Before I think every task shows the project, due date, etc. I don't know from when this is happening. I tried to force showing only specific info, but not works.

**Comment by weemoedig** [comment]
Seconding this. I tried enforcing show queries, but alas. 
The only way I managed to implement it was per the plugin settings that will be deprecated.

**Comment by jamiebrynes7** [comment]
This may be the result of the interaction between the plugin settings & the query settings. If the plugin setting is are turned _off_ then that will take precedence over the query setting.

I'd advise leaving the plugin settings as all on and using the query settings to control on per-query basis. This will result in the same behaviour after the deprecated settings are removed.

@tmllull is this the case for you? Or are you experiencing a different issue?

**Comment by RobertTalbert** [comment]
FYI I was encountering this issue too, turned the settings back on but now the project and date show even when I don't put in the "show" part of the query.

**Comment by tmllull** [comment]
> @tmllull is this the case for you? Or are you experiencing a different issue?

Hi @jamiebrynes7, I enabled the dates from the config and now the dates are displayed; thanks for the advice!

So, if I understood it, when plugin options are removed, the fields to show will be controlled directly from the query, but, for now, we need to activate one by one, right?

**Comment by jamiebrynes7** [comment]
Just as a heads up, the relevant plugin settings have been removed as of the latest release, v2.0.0 - so now its just the query settings that should affect whether metadata is shown or not. Hopefully this clears things up!
