### ISSUE TITLE
Can't submit API Token

### ISSUE THREAD

**Issue by dsquared22** [jamiebrynes7/obsidian-todoist-plugin#342]
**Describe the bug**
Just installed Sync with Todoist.  Got my Todoist API token, but when I try to enter it, the submit button is disabled.
![ScreenFloat Shot of Obsidian at Oct 21, 2024 at 10_49_21 PM](https://github.com/user-attachments/assets/ec8ce493-ad26-4f69-b1e4-8d8e9530d001)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Plugin Version  1.13.0
 - Obsidian Version 1.6.7

**Additional context**

**Comment by jamiebrynes7** [comment]
As a heads up, @dsquared22 you may want to rotate your API token that's in the screenshot as anyone could use it to access your information.

The form is meant to give you some kind of feedback (a spinner when validating and either a check or a cross with an error) - but it seems that its possible to get into this state as well, thanks for raising!

**Comment by pauldot708** [comment]
I have experienced exactly this as well.  I have created 3 new API tokens in Todoist but for each it is not possible to click submit button in Todoist plug in

**Comment by tiovialde** [comment]
@pauldot708 it works to click right instead of left, when you add a new API token. I have no idea why it worked, but it did :D

**Comment by jamiebrynes7** [comment]
Hey all, I've changed how the text box responds to changes and when it chooses to validate in the latest release.

I'm hopeful this resolves the issue and the workaround suggested by @tiovialde is no longer required! I'm going to optimistically close this issue, but please feel free to re-open if this still happens on the 2.0.0 release!
