### ISSUE TITLE
High startup time

### ISSUE THREAD

**Issue by mAAdhaTTah** [jamiebrynes7/obsidian-todoist-plugin#347]
**Describe the bug**
The Todoist plugin has a high startup time.

**To Reproduce**
1. Install plugin
2. Configure plugin with API token etc.
3. Close & open Obsidian
4. Check the startup time in the general tab

**Expected behavior**
Most plugins take ~20-100ms or so to start up. Todoist plugin takes closer to 700-800ms.

**Screenshots**

<img width="485" alt="Screenshot 2024-11-05 at 9 11 53 AM" src="https://github.com/user-attachments/assets/c9218cc6-8c58-4f38-8f1e-39b509044c93">

**Desktop (please complete the following information):**
 - Plugin Version v1.13.0
 - Obsidian Version v1.7.5

**Comment by danielbcarvalho** [comment]
Here is even higher: 1,400ms.

Plugin Version v1.13.0
Obsidian Version v1.7.6

Thinking about giving up.

![image](https://github.com/user-attachments/assets/b3e3aa6d-e22f-4d1e-97ef-a3f5bdfb0241)

**Comment by LikeShootingStars** [comment]
Thanks @jamiebrynes7 for looking into this – I'm also struggling here a bit.

Setup:
Plugin Version v1.13.0
Obsidian Version v1.7.7

Startup time: 1,892ms

<img width="464" alt="Screenshot 2024-11-23 at 03 47 58" src="https://github.com/user-attachments/assets/c23a097d-bb62-4a7a-b322-1109f8e3f8a4">

**Comment by zedtools** [comment]
I'm seeing the same. Todoist Sync is 75% of the startup time on my MacBook Pro M1.

Todoist Sync startup time = 3,673 ms.
17 other plugins total startup time = 467ms.

Something is seriously wrong here. Whatever is slowing it down should probably be deferred to after `onload()`.

<img width="484" alt="image" src="https://github.com/user-attachments/assets/fff8fee4-b12b-4996-9b2a-fe48353b76e2">

**Comment by jamiebrynes7** [comment]
Hey all, I've just released v2.0.0 which should resolve the slow startup issue. Turns out we were firing off some requests to the Todoist API when initializing the plugin!

**Comment by zedtools** [comment]
Much better... my startup time reduced from 3,673ms to 38ms.

**Comment by LikeShootingStars** [comment]
Same here – Thanks @jamiebrynes7
