### ISSUE TITLE
Creating tasks in obsidian

### ISSUE THREAD

**Issue by mrDLSable** [jamiebrynes7/obsidian-todoist-plugin#43]
Creating tasks in obsidian is a logical next step in the development of this plugin. Here are some of my ideas on how this could work.

- A command in the command pallet.
- A form in a note.
- A dedicated note that gets read once in a while where you type out tasks like you can do in todoist.

**Comment by argenos** [comment]
Adding a +1 on this! With obsidian's URL scheme it would be neat if the task was prefilled with the link to the note itself. My preference is a hotkey + modal where I can add finishing touches like labels and due dates, before hitting enter and sending it to Todoist.

**Comment by wenlzhang** [comment]
Another possible workflow is as follows:

1. Add a tag, e.g. `#Todoist`, to an item/block (item A) in an Obsidian note (note A)
2. Automatically send item A to Todoist
3. Automatically link item A to an Obsidian note for managing to-dos, e.g. `Todoist.md`
4. One can also embed the desired project in Todoist, e.g. Project Obsidian, in `Todoist.md`, for better reference/comparison

**Comment by jamiebrynes7** [comment]
Released in [v1.6.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.6.0)!
