### ISSUE TITLE
Turning off 'Render labels' setting does not persist

### ISSUE THREAD

**Issue by darthmachina** [jamiebrynes7/obsidian-todoist-plugin#45]
**Describe the bug**
When turning off the 'Render labels' setting in the Settings page, it stays selected and the labels are still shown.

**To Reproduce**
1. Go to 'Todoist' in 'Settings'
2. Click on the 'Render labels' toggle to turn it off
3. Close 'Settings' and see that any labels are still shown in the task list
4. Go back to 'Todoist' in 'Settings' and see that the 'Render labels' toggle is still on

**Expected behavior**
The 'Render labels' toggle stays off and labels are not shown

**Desktop (please complete the following information):**
 - Plugin Version [e.g. 1.3.0]
 - Obsidian Version [e.g. 0.8.15]

**Comment by jamiebrynes7** [comment]
I made a copy-paste error in #42 🤦‍♂️

Will be a quick and easy one to fix!

**Comment by jamiebrynes7** [comment]
Fixed in [`v1.3.1`](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/v1.3.1)
