### ISSUE TITLE
Assign containing workspace-leaf a class

### ISSUE THREAD

**Issue by mrDLSable** [jamiebrynes7/obsidian-todoist-plugin#48]
**Is your feature request related to a problem? Please describe.**
I'm annoyed when switching between computers or changing the layout of my obsidian windows that task word-wrap changes.

**Describe the solution you'd like**
Assigning a class to the workspace-leaf that contains the todoist stuff would give me the ability to give that leaf a fixed width.

**Describe alternatives you've considered**
Sucking the mild annoyance up and hiding the overflow of the task title, either on a hidden second line or just letting it horizontally overflow outside of the leaf.

**Additional context**
Not much to say, just that it's not really that important or something that many people will use, but it would still be nice. It would also give me the ability to call the markdown-preview-view and markdown-preview-section in the specific leaf.

**Comment by jamiebrynes7** [comment]
Released in [`v1.4.0`](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/v1.4.0)! 🎉
