### ISSUE TITLE
Send obsidian file as task in todoist

### ISSUE THREAD

**Issue by mafsi** [jamiebrynes7/obsidian-todoist-plugin#59]
**Is your feature request related to a problem? Please describe.**
Reverse task in Todoist

**Describe the solution you'd like**
I would like to send my current page I'm working in Obsidian as a task in todoist.

**Comment by jamiebrynes7** [comment]
Do you mean something like a command like:

> Send current page to Todoist

And it would create a task in Todoist with a URI to the current vault/page combo? 

If so, sounds related (but not the same!) as #43. There's probably a whole host of possibilities there.

**Comment by mafsi** [comment]
> > Send current page to Todoist
> 
> And it would create a task in Todoist with a URI to the current vault/page combo?

Yes, this one.

**Comment by jamiebrynes7** [comment]
Released in [v1.6.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.6.0)!
