### ISSUE TITLE
Bug with overdue tasks

### ISSUE THREAD

**Issue by greenmanspirit** [jamiebrynes7/obsidian-todoist-plugin#60]
Per our discord conversation:

What I am seeing is that I see overdue daily repeating tasks right away and non-repeating tasks two days after they are due. So Saturdays showed up Monday and Sundays showed up Tuesday. What I expect to see is my overdue tasks as soon as they are overdue.

**Comment by jamiebrynes7** [comment]
Hmm I'm unable to reproduce this unfortunately. 😕

I have a fair few non-repeating overdue tasks from yesterday and they all appear just fine.
