### ISSUE TITLE
Where to add the API token (Obsidian 0.9.13)

### ISSUE THREAD

**Issue by Ceolobo** [jamiebrynes7/obsidian-todoist-plugin#61]
I installed the plugin through the Obsidian installer in Obsidian 0.9.13, but I don't understand where to put the Todoist API token. in the vault/.obsidian folder there is no "todoist-token" file or folder and creating a .txt or .json file with that name myself doesn't seem to work.

**Comment by biodroit** [comment]
I have the same question... How did you resolve it?

**Comment by Ceolobo** [comment]
I made a file without a file extension with Atom editor and copied the API token into that. Saved the file in the vault/.obsidian directory, and then when I restarted Obsidian it worked as intended.

**Comment by biodroit** [comment]
Awesome!  I'll try that.  Thank you!

**Comment by biodroit** [comment]
Confirming that it worked!  Thank you. I was getting caught up with the extension name as well.
