### ISSUE TITLE
Add support for the Outlook plugin / markdown links

### ISSUE THREAD

**Issue by Wittionary** [jamiebrynes7/obsidian-todoist-plugin#67]
**Is your feature request related to a problem? Please describe.**
Tasks added through the Outlook plugin are displayed as a user-unfriendly paragraph of symbols followed by the email subject.
![image](https://user-images.githubusercontent.com/1906737/100184942-3e53e100-2ea8-11eb-94d7-b2fd1c87b30f.png)

**Describe the solution you'd like**
I'd *really* like to see it displayed as a clickable link as it is in the Todoist app. Clicking on it opens the email in Outlook.
![image](https://user-images.githubusercontent.com/1906737/100185308-229d0a80-2ea9-11eb-8dc7-91c1aedce361.png)

**Describe alternatives you've considered**
Right now I just exclude email tasks, `@type_email`, from the filter.

**Additional context**
Regarding markdown links - if this is at all in the same vein - there are two different styles:
![image](https://user-images.githubusercontent.com/1906737/100185646-f46bfa80-2ea9-11eb-8f83-ca55f7ec7314.png)
_If this should be added as a separate feature request, let me know. I kinda figured they were similar._ 😅 ¯\\_(ツ)_/¯

Let me know if/how I can help dig up info or troubleshoot. My Javascript ability is next to nil, but I am technical.

**Comment by jamiebrynes7** [comment]
Hey @Wittionary, Markdown links should render correctly in [v1.7.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.7.0)! 

As for the Outlook links, this isn't valid Markdown (in fact it clashes with Obsidian `[[internal links]]`), I'm also not a user of this functionality which makes it hard to test. I'm not going to implement this side of things, but am happy to review a PR for it.
