### ISSUE TITLE
Connection error behind corporate proxy

### ISSUE THREAD

**Issue by rui-nar** [jamiebrynes7/obsidian-todoist-plugin#68]
**Describe the bug**
I cannot access my todoist tasks  with your plugin behind my corporate proxy (but I can access them via Chrome)

**Screenshots**
app.5a1cc6ab6b6df8c9f7d7.js?__WB_REVISION__=b0820e3e10926456d1a2848df5e7b8c7:formatted:64871 WebSocket connection to 'wss://ws.todoist.com/ws?token=19efa7e0dbe3da7f' failed: Error during WebSocket handshake: Unexpected response code: 503
(anonymous) @ app.5a1cc6ab6b6df8c9f7d7.js?__WB_REVISION__=b0820e3e10926456d1a2848df5e7b8c7:formatted:64871
(anonymous) @ app.5a1cc6ab6b6df8c9f7d7.js?__WB_REVISION__=b0820e3e10926456d1a2848df5e7b8c7:formatted:64908
i @ vendor.f9955d70ecf8f822e0fd.js:90

**Desktop (please complete the following information):**
 - Plugin Version 1.5.0
 - Obsidian Version 0.9.15

**Additional context**
I'm behind a (secure) corporate proxy which "filters" our internet traffic ... access to Todoist via Chrome and the Web UI works with no issue.

**Comment by jamiebrynes7** [comment]
I'm rather confused by this as the plugin only makes REST API calls, it never opens a WebSocket connection like you see above. 

In fact, the Todoist Web UI (in Chrome) _does_ make WebSocket connections, and the stack trace that you've pasted looks exactly like the ones I see there. 

Do you happen to have an `iframe` embed of Todoist in Obsidian as well? 

The requests that this plugin makes look like:

![image](https://user-images.githubusercontent.com/13353733/100256572-dbf8f000-2f3c-11eb-9815-afba2fc9f041.png)

Based on what you've described, I would expect these to be failed too, but if that traffic is filtered by your corporate proxy there's not a lot I can do about that. If you can get `api.todoist.com` allowed through the proxy filter then this plugin should work again.

**Comment by rui-nar** [comment]
You were SPOT ON !! I did have an iframe of Todoist !!
Removing that and restarting obsidian solved the problem !

Amazing support!

I now NEEEEEEEEED 2-way interaction to work (#43) so I'm a happy man :)

**Comment by jamiebrynes7** [comment]
I'm glad that solved the issue for you.. 🥳 


... and #43 is next up on my list when I find the time & motivation 😁
