### ISSUE TITLE
Uncompletable tasks in the sync plugin should not get a checkbox

### ISSUE THREAD

**Issue by jorgb** [jamiebrynes7/obsidian-todoist-plugin#69]
When rendering from a query, some task titles returned are:

`* Deadline on XYZ`

This gets to be rendered as;

- [ ] * Deadline on XYZ

But to Todoist it is an not completable task, so it would be great of your fantastic sync plugin would honor that 👍 
Keep up the good work!

**Comment by jamiebrynes7** [comment]
Hey @jorgb, the input elements for uncompletable tasks will be disabled in [v1.7.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.7.0)!

**Comment by jorgb** [comment]
That's awesome news, thanks!
