### ISSUE TITLE
Option to show count of tasks

### ISSUE THREAD

**Issue by connordodge** [jamiebrynes7/obsidian-todoist-plugin#70]
**Is your feature request related to a problem? Please describe.**
No problem. Just a feature request

**Describe the solution you'd like**
I would like to specify in my code block to show the count of tasks. Either a boolean property like "showCount": true or the ability to add it inline to the name like "Name - {taskCount}" 

**Describe alternatives you've considered**
No alternatives.

**Additional context**
None.

**Comment by jamiebrynes7** [comment]
Hey @connordodge, this should be implemented in [v1.7.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.7.0)! 

You can use `{task_count}` in the query name as a template for this!
