### ISSUE TITLE
Todoist tasks with markdown show the markdown text instead of the display version of the text even in display mode

### ISSUE THREAD

**Issue by connordodge** [jamiebrynes7/obsidian-todoist-plugin#71]
**Describe the bug**
In Todoist I can add hyper links to a task by using the markdown format for hyperlink,s and I can use other markdown markers to indicate things like bold, italics, etc. The markdown is shown in the Todoist block instead of the modified version of the text. `[Task text](link)`

**To Reproduce**
1. Add a task to Todoist with the label "reproduce_bug". The text of that task should include hyperlinked text use the markdown format in the description, and can use other markdown markers like *italics* or __bold__
2. In obsidian create a todoist code block like
```todoist
{
"name": "",
"filter": " @reproduce_bug",
"sorting": []
}
```
or just make sure your filter includes the added task
3. View the Todoist code block in display mode
4. You will see the markdown instead of the display versions of the text
![Screen Shot 2020-11-30 at 8 44 08 AM](https://user-images.githubusercontent.com/12689103/100631482-fe965a80-32e8-11eb-9b95-e45ddfd42ac7.png)

**Expected behavior**
You should see the hyperlinked text instead of the markdown

**Screenshots**
Screenshot attached

**Desktop (please complete the following information):**
 - Plugin Version 1.5.0
 - Obsidian Version 0.9.15

**Additional context**

**Comment by connordodge** [comment]
I suppose this could also be considered a feature request, to honor markdown syntax when pulling tasks through, so you can mark it however you want. I love the plugin by the way! It is fantastic.

**Comment by jamiebrynes7** [comment]
Yeah I'd consider this a feature request as its simply not implemented yet! 

Related to: #72 and #67

**Comment by jamiebrynes7** [comment]
Hey @connordodge, this should be implemented in [v1.7.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.7.0)!
