### ISSUE TITLE
Clickable double square brackets link in task

### ISSUE THREAD

**Issue by Klaudioz** [jamiebrynes7/obsidian-todoist-plugin#72]
I've created a task over Todoist with the name in double brackets but in Obsidian I can't click on it.

Example:
![image](https://user-images.githubusercontent.com/73141990/101092160-71683580-3576-11eb-88ce-f5a169e2ee54.png)

In this case: **Swing Trading** is a valid link.

**Comment by jamiebrynes7** [comment]
Hey @Klaudioz, clickable internal links should be implemented in [v1.7.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.7.0)!

**Comment by Klaudioz** [comment]
I'm going to check the new version now. Thank you !!
