### ISSUE TITLE
Not all tasks showing in Obsidian

### ISSUE THREAD

**Issue by macbikegeek** [jamiebrynes7/obsidian-todoist-plugin#73]
**Describe the bug**
I have a bunch of tasks in Todoist for Today and Overdue but only 1 Overdue and 1 Today are being returned.

**To Reproduce**
```todoist
{
"name": "My Tasks",
"filter": "today | overdue"
}
```
**Expected behavior**
All the tasks for today and overdue

**Screenshots**
<img width="640" alt="Screen Shot 2020-12-08 at 1 23 37 PM" src="https://user-images.githubusercontent.com/20144822/101531241-971b8300-3958-11eb-996b-2baea4729db9.png">
<img width="1413" alt="Screen Shot 2020-12-08 at 1 24 15 PM" src="https://user-images.githubusercontent.com/20144822/101531304-ad294380-3958-11eb-96b1-e8838fb47793.png">

**Desktop (please complete the following information):**
 - Plugin Version 1.5.0
 - Obsidian Version 0.9.22

**Additional context**
It was working fine until late yesterday. Not sure when 0.9.22 update autoupdated

**Comment by jamiebrynes7** [comment]
Hi @macbikegeek are there any errors in the dev tools console (Command+Option+I)? 

I'm unable to reproduce this with 60+ overdue tasks on the same plugin/Obsidian versions.

**Comment by macbikegeek** [comment]
There are but I'm not sure they are relevant. Happy to turn things off if needed to debug.
<img width="556" alt="Screen Shot 2020-12-08 at 1 58 45 PM" src="https://user-images.githubusercontent.com/20144822/101534995-989b7a00-395d-11eb-95f2-4951f9a97d72.png">

**Comment by macbikegeek** [comment]
Auto update just finished - still just the two tasks picked up.
<img width="549" alt="Screen Shot 2020-12-08 at 2 07 37 PM" src="https://user-images.githubusercontent.com/20144822/101535751-bd442180-395e-11eb-8784-5a90af2e2dee.png">

**Comment by macbikegeek** [comment]
OK, totally baffled. It's working now. The only thing I changed was re-activating the Mind Map plugin

**Comment by jamiebrynes7** [comment]
Well, I'm glad its working for you again! Although it is a puzzling one!
