### ISSUE TITLE
when sorting by "priority", I would like to be able to group them and see group headers (Priority1, Priority2)

### ISSUE THREAD

**Issue by rui-nar** [jamiebrynes7/obsidian-todoist-plugin#74]
**Is your feature request related to a problem? Please describe.**
When I sort by priority, I would like to be able to group by priority as well and see the project name as metadata. This would also apply to grouping by label.

**Describe the solution you'd like**
See the tasks grouped by priority with Priority Group headers. Ideally, with an "alias" options, I would like to be able to rename "Priority 1" to "urgent".

**Describe alternatives you've considered**
There are no alternatives

**Something like**
{
"name": "My Tasks",
"filter": "p1|p2|p3|No priority",
"group": "priority", //or "label" or "project"
"sorting": ["date"],
 "alias": {"p1": "Urgent", "p2": "Next"}
}

**Comment by jamiebrynes7** [comment]
Hey @rui-nar, you can now do this as of the [latest release](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.13.0) like so:

```
filter: "today | overdue"
groupBy: priority
```
