### ISSUE TITLE
see complete subtasks as strikethrough tasks

### ISSUE THREAD

**Issue by rui-nar** [jamiebrynes7/obsidian-todoist-plugin#75]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
i'd like to be able to see complete sub-tasks, like in the webUI maybe through an additional option "seeCompleted": true

**Comment by jamiebrynes7** [comment]
Hey @rui-nar sadly this isn't possible with the public Todoist API. Completed tasks are not available through this. 

Their webapp must use a different backend to access this data.
