### ISSUE TITLE
Styling seems to be broken

### ISSUE THREAD

**Issue by nadavc** [jamiebrynes7/obsidian-todoist-plugin#77]
**Describe the bug**
Using the latest versions of Obsidian and the Todoist plugin, I'm able to see tasks displayed in preview, but the styling seems to be off. This is with the default theme applied only.

**To Reproduce**
1. Install the plugin from the plugin browser
2. Configure the `.todoist-token` in the `.obsidian` directory
3. Restart Obsidian
4. Add the `todoist` code block
5. Put on preview

**Expected behavior**
A todo list styled like in the readme screenshots

**Screenshots**
<img width="840" alt="Vault2 - Obsidian v0 10 1 2020-12-23 09-56-15" src="https://user-images.githubusercontent.com/610392/103024660-24d4a200-4505-11eb-8654-b5fbfff4fc74.png">

**Desktop (please complete the following information):**
 - Plugin Version 1.5.0
 - Obsidian Version 0.10.1

**Additional context**

**Comment by nadavc** [comment]
I see this works out of the box with the [Clair-de-lune theme](https://github.com/jamiebrynes7/clair-de-lune-obsidian-theme). Leaving the bug open in case this isn't intentional.

**Comment by jamiebrynes7** [comment]
This plugin pre-dates the official plugin API which introduced the ability to ship default CSS along with the plugin. I can add some default CSS to rectify this on the official (and hopefully most other!) themes.

**Comment by jamiebrynes7** [comment]
Released in [v1.6.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.6.0)!
