### ISSUE TITLE
Missing commands with v1.6

### ISSUE THREAD

**Issue by rui-nar** [jamiebrynes7/obsidian-todoist-plugin#86]
**Describe the bug**
With v1.6 I have access to the command 'Refresh Metadata' but not to the commands 'Add Todoist task' and ''Add Todoist task with the current page'

**Screenshots**
![image](https://user-images.githubusercontent.com/10478175/103647489-af80bc80-4f5b-11eb-921f-8049859114f9.png)

**Desktop (please complete the following information):**
 - Plugin Version 1.6.0
 - Obsidian Version 0.10.6

**Comment by jamiebrynes7** [comment]
Hi @rui-nar, are there any errors in the dev console?

**Comment by rui-nar** [comment]
none that I can see @jamiebrynes7

**Comment by rui-nar** [comment]
![image](https://user-images.githubusercontent.com/10478175/103648750-9ed14600-4f5d-11eb-950d-eeb1d12fdf63.png)

**Comment by jamiebrynes7** [comment]
Hmm, I'm not sure how you have one but not the other as they are registered sequentially in the code.

Have you restarted Obsidian since updating the plugin?

**Comment by rui-nar** [comment]
I do feel bad now .. I just restarted Obsidian and all commands appeared :(
so sorry for taking your time on this stupid issue

**Comment by jamiebrynes7** [comment]
No worries 😄 

It happens to the best of us, and I've learned something too!
