### ISSUE TITLE
Code does not resolve after restart

### ISSUE THREAD

**Issue by rui-nar** [jamiebrynes7/obsidian-todoist-plugin#88]
**Describe the bug**
every time I restart Obsidian, the todoist code doesn't resolve. I have to modify the code block (i usually remove "}" to create an error and then add it back again) to have it refresh

**To Reproduce**
1. Restart Obsidian
2. code does not resolve

**Screenshots**
![image](https://user-images.githubusercontent.com/10478175/104288978-d3428600-54b8-11eb-91fa-3b465bb1357f.png)
![image](https://user-images.githubusercontent.com/10478175/104288946-c7ef5a80-54b8-11eb-85b2-f4b48065fafb.png)

**Desktop (please complete the following information):**
 - Plugin Version 1.6.0
 - Obsidian Version 0.10.6 (and 0.10.7)

**Comment by jamiebrynes7** [comment]
Hey @rui-nar, I noticed this myself and finally tracked the issue down. I've fixed and released this in [v1.6.2](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.6.2)!
