### ISSUE TITLE
Give task list a custom class so styling can be done without affecting other lists

### ISSUE THREAD

**Issue by mrDLSable** [jamiebrynes7/obsidian-todoist-plugin#95]
**Is your feature request related to a problem? Please describe.**
I want to give the task list padding of 0px, but doing so with the ```contains-task-list``` class also affects normal task lists in other .md files.

**Describe the solution you'd like**
I propose adding a ```todoist-task-list``` class to the task lists to allow for custom styling.

**Comment by jamiebrynes7** [comment]
This feature is now available in [v1.8.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.8.0)!
