### ISSUE TITLE
Add option to disable Open in app feature, as it dows not work in Windows

### ISSUE THREAD

**Issue by frvkl** [jamiebrynes7/obsidian-todoist-plugin#97]
The todoist://task?id= uri is not supported in the Todoist app for windows.

It would be great if we can have a toggle in settings to turn off the link in the context menu 'Open task in Todoist (app)'.

The link in the context menu to 'Open task in Todoist (web)' is sufficient for the windows user.

**Comment by isle99** [comment]
Do you know if they plan to fix the url not redirecting properly in the Todoist desktop app?

**Comment by jamiebrynes7** [comment]
> Do you know if they plan to fix the url not redirecting properly in the Todoist desktop app?

Unfortunately not, you'd need to ask Todoist support if/when they'll support this
