### ISSUE TITLE
Markdown Preview output is not rendered when exporting to PDF

### ISSUE THREAD

**Issue by frvkl** [jamiebrynes7/obsidian-todoist-plugin#98]
When exporting a note to PDF in Obsidian, the output is not printed to the PDF. Instead the codeblock is printed to the PDF.

**To Reproduce**
1. Add Todoist codeblock to a note
2. Check if output is shown correctly in Markdown preview mode.
3. Export the note to PDF
4. See codeblock printed on PDF instead of the markdown output

**Expected behavior**
The Markdown Preview output printed to the PDF

**Screenshots**

Editor:
![shot_210223_204727](https://user-images.githubusercontent.com/19724110/108899189-6d4d3080-7618-11eb-863e-77b0a3e656fa.png)

Markdown Preview
![shot_210223_204906](https://user-images.githubusercontent.com/19724110/108899328-979eee00-7618-11eb-83ba-c0ecd6f82854.png)

Rendered in exported PDF 
![shot_210223_204657](https://user-images.githubusercontent.com/19724110/108899190-6de5c700-7618-11eb-80e9-bbd177981476.png)

**Desktop (please complete the following information):**
 - Plugin v1.7.0
 - Obsidian v0.11.0

**Additional context**
I inquired in the Obsidian forum: https://forum.obsidian.md/t/plugin-output-from-codefence-not-rendered-in-pdf-export/13497
The moderator asked me to submit a ticket here.

**Comment by jamiebrynes7** [comment]
As far as I'm aware, plugins cannot modify the PDF rendering output. At least, there doesn't seem to be any references to it in the plugin API.

Obsidian would need to expose hooks for that process before I can implement this.

**Comment by argenos** [comment]
Here's a tip from Licat:

> The PDF export "waits" for some async tasks to execute. If the plugin author didn't properly return the async task, then we won't wait for them to render their portion, so nothing gets rendered. Specifically for the todoist plugin, they should mark this function as async and wait for the query to execute so that we can properly render the PDF: https://github.com/jamiebrynes7/obsidian-todoist-plugin/blob/be86a3b6035f0693f0eecbb81032e318c0f2f6aa/src/queryInjector.ts#L22

**Comment by leovannier** [comment]
Hi Jamie, +1 for this feature.

**Comment by jamiebrynes7** [comment]
Going to leave this one open @frvkl, as it seems you're not the only one that might want this.
