### ISSUE TITLE
YAML entry

### ISSUE THREAD

**Issue by yonaskolb** [jamiebrynes7/obsidian-todoist-plugin#99]
**Is your feature request related to a problem? Please describe.**
Entering json into the code blocks is time consuming and fiddly, it's not a great writing experience

**Describe the solution you'd like**
I would love to be able to define the same properties but in yaml

```todoist
name: My Tasks
filter: today | overdue
```
If it's wrapped in curly braces it could decode in json, and if not try yml

**Describe alternatives you've considered**
An editor? But yml entry is just as fast as any ui

**Additional context**
Really love the plugin! 🙏

**Comment by jamiebrynes7** [comment]
This has been released in v1.11.0 as an option alongisde JSON
